
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.templates.email.create;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.templates.email.create.params.CreateRequest;


public class CreateClient {
    protected final BaseClient baseClient;

    public CreateClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * Create Email Template
    *
    * > Use this endpoint to create email templates on the Braze dashboard.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `templates.email.create` permission.
    *
    * These templates will be available on the **Templates & Media** page. The response from this endpoint will include a field for `email_template_id`, which can be used to update the template in subsequent API calls.
    *
    * Users’ email subscription status can be updated and retrieved via Braze using a RESTful API. You can use the API to set up bi-directional sync between Braze and other email systems or your own database. All API requests are made over HTTPS.
    *
    * ### Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ### Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `template_name` | Required | String | Name of your email template. |
    * | `subject` | Required | String | Email template subject line. |
    * | `body` | Required | String | Email template body that may include HTML. |
    * | `plaintext_body` | Optional | String | A plaintext version of the email template body. |
    * | `preheader` | Optional | String | Email preheader used to generate previews in some clients. |
    * | `tags` | Optional | String | [Tags](https://www.braze.com/docs/user_guide/administrative/app_settings/manage_app_group/tags/) must already exist. |
    * | `should_inline_css` | Optional | Boolean | Enables or disables the `inline_css` feature per template. If not provided, Braze will use the default setting for the app group. One of `true` or `false` is expected. |
    *
    * ### Possible errors
    *
    * The following table lists possible returned errors and their associated troubleshooting steps, if applicable.
    *
    * | Error | Troubleshooting |
    * | --- | --- |
    * | Template name is required | Enter a template name. |
    * | Tags must be an array | Tags must be formatted as an array of strings, for example `["marketing", "promotional", "transactional"]`. |
    * | All tags must be strings | Make sure your tags are encapsulated in quotes (`""`). |
    * | Some tags could not be found | To add a tag when creating an email template, the tag must already exist in Braze. |
    * | Email must have valid Content Block names | The email contains Content Blocks that don't exist in this environment. |
    * | Invalid value for `should_inline_css`. One of `true` or `false` was expected | This parameter only accepts boolean values (true or false). Make sure the value for `should_inline_css` is not encapsulated in quotes (`""`), which causes the value to be sent as a string instead. |
    *
    * POST /templates/email/create
    */
    public Map<?, ?> create(CreateRequest request) {
        return create(request, null);
    }


    /**
    * Create Email Template
    *
    * > Use this endpoint to create email templates on the Braze dashboard.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `templates.email.create` permission.
    *
    * These templates will be available on the **Templates & Media** page. The response from this endpoint will include a field for `email_template_id`, which can be used to update the template in subsequent API calls.
    *
    * Users’ email subscription status can be updated and retrieved via Braze using a RESTful API. You can use the API to set up bi-directional sync between Braze and other email systems or your own database. All API requests are made over HTTPS.
    *
    * ### Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ### Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `template_name` | Required | String | Name of your email template. |
    * | `subject` | Required | String | Email template subject line. |
    * | `body` | Required | String | Email template body that may include HTML. |
    * | `plaintext_body` | Optional | String | A plaintext version of the email template body. |
    * | `preheader` | Optional | String | Email preheader used to generate previews in some clients. |
    * | `tags` | Optional | String | [Tags](https://www.braze.com/docs/user_guide/administrative/app_settings/manage_app_group/tags/) must already exist. |
    * | `should_inline_css` | Optional | Boolean | Enables or disables the `inline_css` feature per template. If not provided, Braze will use the default setting for the app group. One of `true` or `false` is expected. |
    *
    * ### Possible errors
    *
    * The following table lists possible returned errors and their associated troubleshooting steps, if applicable.
    *
    * | Error | Troubleshooting |
    * | --- | --- |
    * | Template name is required | Enter a template name. |
    * | Tags must be an array | Tags must be formatted as an array of strings, for example `["marketing", "promotional", "transactional"]`. |
    * | All tags must be strings | Make sure your tags are encapsulated in quotes (`""`). |
    * | Some tags could not be found | To add a tag when creating an email template, the tag must already exist in Braze. |
    * | Email must have valid Content Block names | The email contains Content Blocks that don't exist in this environment. |
    * | Invalid value for `should_inline_css`. One of `true` or `false` was expected | This parameter only accepts boolean values (true or false). Make sure the value for `should_inline_css` is not encapsulated in quotes (`""`), which causes the value to be sent as a string instead. |
    *
    * POST /templates/email/create
    */
    public Map<?, ?> create(CreateRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/templates/email/create")
            .method("POST")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .setJsonBody(request.getData())
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
