
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.preferencecenter;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.preferencecenter.v1.V1Client;


public class PreferenceCenterClient {
    protected final BaseClient baseClient;
    protected final Supplier<V1Client> v1;
    public PreferenceCenterClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.v1 = Suppliers.memoize(() -> new V1Client(baseClient));
    }

    public V1Client v1() {
        return this.v1.get();
    }
}
