
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.templates.email.info.params;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * ListRequest
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListRequest.Builder.class)
public final class ListRequest {
    /**
     * (Required) String
     *
     * See [email template's API identifier](https://www.braze.com/docs/api/identifier_types/).
     */
    private final Optional<String> emailTemplateId;

    private ListRequest(
        Optional<String> emailTemplateId
    ) {
        this.emailTemplateId = emailTemplateId;
    }

    /**
     * Retrieves value for `emailTemplateId`
     * (Required) String
     *
     * See [email template's API identifier](https://www.braze.com/docs/api/identifier_types/).
     */
    @JsonProperty("email_template_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getEmailTemplateId() {
        return emailTemplateId.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof ListRequest && equalTo((ListRequest) other);
    }

    private boolean equalTo(ListRequest other) {
        return
            emailTemplateId.equals(other.emailTemplateId)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.emailTemplateId
               );
    }

    @Override
    public String toString() {
        return "ListRequest{" +
               "emailTemplateId=" + emailTemplateId +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        /**
         * (Required) String
         *
         * See [email template's API identifier](https://www.braze.com/docs/api/identifier_types/).
         */
        private Optional<String> emailTemplateId = Optional.empty();

        private Builder() {}

        public Builder from(ListRequest other) {
            emailTemplateId(other.getEmailTemplateId());
            return this;
        }

        /**
         * Sets value for `emailTemplateId`
         * (Required) String
         *
         * See [email template's API identifier](https://www.braze.com/docs/api/identifier_types/).
         */
        @JsonSetter("email_template_id")
        public Builder emailTemplateId(String emailTemplateId) {
            this.emailTemplateId = Optional.ofNullable(emailTemplateId);

            return this;
        }

        public Builder emailTemplateId(Optional<String> emailTemplateId) {
            this.emailTemplateId = emailTemplateId;
            return this;
        }


        public ListRequest build() {
            return new ListRequest(
                       emailTemplateId
                   );
        }
    }

}



