
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.segments.details.params;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * ListRequest
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListRequest.Builder.class)
public final class ListRequest {
    /**
     * (Required) String
     *
     * See [Segment API identifier](https://www.braze.com/docs/api/identifier_types/).
     *
     * The `segment_id` for a given segment can be found in your **Settings > Setup and Testing > API Keys** within your Braze account or you can use the [Segment List Endpoint](https://www.braze.com/docs/api/endpoints/export/get_segment/).
     */
    private final Optional<String> segmentId;

    private ListRequest(
        Optional<String> segmentId
    ) {
        this.segmentId = segmentId;
    }

    /**
     * Retrieves value for `segmentId`
     * (Required) String
     *
     * See [Segment API identifier](https://www.braze.com/docs/api/identifier_types/).
     *
     * The `segment_id` for a given segment can be found in your **Settings > Setup and Testing > API Keys** within your Braze account or you can use the [Segment List Endpoint](https://www.braze.com/docs/api/endpoints/export/get_segment/).
     */
    @JsonProperty("segment_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getSegmentId() {
        return segmentId.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof ListRequest && equalTo((ListRequest) other);
    }

    private boolean equalTo(ListRequest other) {
        return
            segmentId.equals(other.segmentId)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.segmentId
               );
    }

    @Override
    public String toString() {
        return "ListRequest{" +
               "segmentId=" + segmentId +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        /**
         * (Required) String
         *
         * See [Segment API identifier](https://www.braze.com/docs/api/identifier_types/).
         *
         * The `segment_id` for a given segment can be found in your **Settings > Setup and Testing > API Keys** within your Braze account or you can use the [Segment List Endpoint](https://www.braze.com/docs/api/endpoints/export/get_segment/).
         */
        private Optional<String> segmentId = Optional.empty();

        private Builder() {}

        public Builder from(ListRequest other) {
            segmentId(other.getSegmentId());
            return this;
        }

        /**
         * Sets value for `segmentId`
         * (Required) String
         *
         * See [Segment API identifier](https://www.braze.com/docs/api/identifier_types/).
         *
         * The `segment_id` for a given segment can be found in your **Settings > Setup and Testing > API Keys** within your Braze account or you can use the [Segment List Endpoint](https://www.braze.com/docs/api/endpoints/export/get_segment/).
         */
        @JsonSetter("segment_id")
        public Builder segmentId(String segmentId) {
            this.segmentId = Optional.ofNullable(segmentId);

            return this;
        }

        public Builder segmentId(Optional<String> segmentId) {
            this.segmentId = segmentId;
            return this;
        }


        public ListRequest build() {
            return new ListRequest(
                       segmentId
                   );
        }
    }

}



