
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.email.bounce;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.email.bounce.remove.RemoveClient;


public class BounceClient {
    protected final BaseClient baseClient;
    protected final Supplier<RemoveClient> remove;
    public BounceClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.remove = Suppliers.memoize(() -> new RemoveClient(baseClient));
    }

    public RemoveClient remove() {
        return this.remove.get();
    }
}
