
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.users;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.users.alias.AliasClient;
import com.yourorg.brazejava.resources.users.delete.DeleteClient;
import com.yourorg.brazejava.resources.users.export.ExportClient;
import com.yourorg.brazejava.resources.users.externalids.ExternalIdsClient;
import com.yourorg.brazejava.resources.users.identify.IdentifyClient;
import com.yourorg.brazejava.resources.users.merge.MergeClient;
import com.yourorg.brazejava.resources.users.track.TrackClient;


public class UsersClient {
    protected final BaseClient baseClient;
    protected final Supplier<AliasClient> alias;
    protected final Supplier<DeleteClient> delete;
    protected final Supplier<ExportClient> export;
    protected final Supplier<ExternalIdsClient> externalIds;
    protected final Supplier<IdentifyClient> identify;
    protected final Supplier<MergeClient> merge;
    protected final Supplier<TrackClient> track;
    public UsersClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.alias = Suppliers.memoize(() -> new AliasClient(baseClient));
        this.delete = Suppliers.memoize(() -> new DeleteClient(baseClient));
        this.export = Suppliers.memoize(() -> new ExportClient(baseClient));
        this.externalIds = Suppliers.memoize(() -> new ExternalIdsClient(baseClient));
        this.identify = Suppliers.memoize(() -> new IdentifyClient(baseClient));
        this.merge = Suppliers.memoize(() -> new MergeClient(baseClient));
        this.track = Suppliers.memoize(() -> new TrackClient(baseClient));
    }

    public AliasClient alias() {
        return this.alias.get();
    }

    public DeleteClient delete () {
        return this.delete.get();
    }

    public ExportClient export() {
        return this.export.get();
    }

    public ExternalIdsClient externalIds() {
        return this.externalIds.get();
    }

    public IdentifyClient identify() {
        return this.identify.get();
    }

    public MergeClient merge() {
        return this.merge.get();
    }

    public TrackClient track() {
        return this.track.get();
    }
}
