
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.campaigns.dataseries.params;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * ListRequest
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListRequest.Builder.class)
public final class ListRequest {
    /**
     * (Required) String
     *
     * See [campaign API identifier](https://www.braze.com/docs/api/identifier_types/).
     *
     * The `campaign_id` for API campaigns can be found at **Settings > Setup and Testing > API Keys** and the **Campaign Details** page within your dashboard, or you can use the [List campaigns endpoint](https://www.braze.com/docs/api/endpoints/export/campaigns/get_campaigns/).
     */
    private final Optional<String> campaignId;
    /**
     * (Optional) Datetime ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string)
     *
     * Date on which the data series should end. Defaults to time of the request.
     */
    private final Optional<String> endingAt;
    /**
     * (Required) Integer
     *
     * Max number of days before `ending_at` to include in the returned series. Must be between 1 and 100 (inclusive).
     */
    private final Optional<Integer> length;

    private ListRequest(
        Optional<String> campaignId,
        Optional<String> endingAt,
        Optional<Integer> length
    ) {
        this.campaignId = campaignId;
        this.endingAt = endingAt;
        this.length = length;
    }

    /**
     * Retrieves value for `campaignId`
     * (Required) String
     *
     * See [campaign API identifier](https://www.braze.com/docs/api/identifier_types/).
     *
     * The `campaign_id` for API campaigns can be found at **Settings > Setup and Testing > API Keys** and the **Campaign Details** page within your dashboard, or you can use the [List campaigns endpoint](https://www.braze.com/docs/api/endpoints/export/campaigns/get_campaigns/).
     */
    @JsonProperty("campaign_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getCampaignId() {
        return campaignId.orElse(null);
    }

    /**
     * Retrieves value for `endingAt`
     * (Optional) Datetime ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string)
     *
     * Date on which the data series should end. Defaults to time of the request.
     */
    @JsonProperty("ending_at")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getEndingAt() {
        return endingAt.orElse(null);
    }

    /**
     * Retrieves value for `length`
     * (Required) Integer
     *
     * Max number of days before `ending_at` to include in the returned series. Must be between 1 and 100 (inclusive).
     */
    @JsonProperty("length")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Integer getLength() {
        return length.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof ListRequest && equalTo((ListRequest) other);
    }

    private boolean equalTo(ListRequest other) {
        return
            campaignId.equals(other.campaignId) &&

            endingAt.equals(other.endingAt) &&

            length.equals(other.length)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.campaignId,
                   this.endingAt,
                   this.length
               );
    }

    @Override
    public String toString() {
        return "ListRequest{" +
               "campaignId=" + campaignId +
               "endingAt=" + endingAt +
               "length=" + length +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        /**
         * (Required) String
         *
         * See [campaign API identifier](https://www.braze.com/docs/api/identifier_types/).
         *
         * The `campaign_id` for API campaigns can be found at **Settings > Setup and Testing > API Keys** and the **Campaign Details** page within your dashboard, or you can use the [List campaigns endpoint](https://www.braze.com/docs/api/endpoints/export/campaigns/get_campaigns/).
         */
        private Optional<String> campaignId = Optional.empty();
        /**
         * (Optional) Datetime ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string)
         *
         * Date on which the data series should end. Defaults to time of the request.
         */
        private Optional<String> endingAt = Optional.empty();
        /**
         * (Required) Integer
         *
         * Max number of days before `ending_at` to include in the returned series. Must be between 1 and 100 (inclusive).
         */
        private Optional<Integer> length = Optional.empty();

        private Builder() {}

        public Builder from(ListRequest other) {
            campaignId(other.getCampaignId());
            endingAt(other.getEndingAt());
            length(other.getLength());
            return this;
        }

        /**
         * Sets value for `campaignId`
         * (Required) String
         *
         * See [campaign API identifier](https://www.braze.com/docs/api/identifier_types/).
         *
         * The `campaign_id` for API campaigns can be found at **Settings > Setup and Testing > API Keys** and the **Campaign Details** page within your dashboard, or you can use the [List campaigns endpoint](https://www.braze.com/docs/api/endpoints/export/campaigns/get_campaigns/).
         */
        @JsonSetter("campaign_id")
        public Builder campaignId(String campaignId) {
            this.campaignId = Optional.ofNullable(campaignId);

            return this;
        }

        public Builder campaignId(Optional<String> campaignId) {
            this.campaignId = campaignId;
            return this;
        }

        /**
         * Sets value for `endingAt`
         * (Optional) Datetime ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string)
         *
         * Date on which the data series should end. Defaults to time of the request.
         */
        @JsonSetter("ending_at")
        public Builder endingAt(String endingAt) {
            this.endingAt = Optional.ofNullable(endingAt);

            return this;
        }

        public Builder endingAt(Optional<String> endingAt) {
            this.endingAt = endingAt;
            return this;
        }

        /**
         * Sets value for `length`
         * (Required) Integer
         *
         * Max number of days before `ending_at` to include in the returned series. Must be between 1 and 100 (inclusive).
         */
        @JsonSetter("length")
        public Builder length(Integer length) {
            this.length = Optional.ofNullable(length);

            return this;
        }

        public Builder length(Optional<Integer> length) {
            this.length = length;
            return this;
        }


        public ListRequest build() {
            return new ListRequest(
                       campaignId,
                       endingAt,
                       length
                   );
        }
    }

}



