
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * CanvasTriggerScheduleCreateCreateBodySchedule
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CanvasTriggerScheduleCreateCreateBodySchedule.Builder.class)
public final class CanvasTriggerScheduleCreateCreateBodySchedule {
    private final Optional<Boolean> atOptimalTime;
    private final Optional<Boolean> inLocalTime;
    private final Optional<String> time;

    private CanvasTriggerScheduleCreateCreateBodySchedule(
        Optional<Boolean> atOptimalTime,
        Optional<Boolean> inLocalTime,
        Optional<String> time
    ) {
        this.atOptimalTime = atOptimalTime;
        this.inLocalTime = inLocalTime;
        this.time = time;
    }

    /**
     * Retrieves value for `atOptimalTime`
     */
    @JsonProperty("at_optimal_time")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Boolean getAtOptimalTime() {
        return atOptimalTime.orElse(null);
    }

    /**
     * Retrieves value for `inLocalTime`
     */
    @JsonProperty("in_local_time")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Boolean getInLocalTime() {
        return inLocalTime.orElse(null);
    }

    /**
     * Retrieves value for `time`
     */
    @JsonProperty("time")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getTime() {
        return time.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof CanvasTriggerScheduleCreateCreateBodySchedule &&
               equalTo((CanvasTriggerScheduleCreateCreateBodySchedule) other);
    }

    private boolean equalTo(CanvasTriggerScheduleCreateCreateBodySchedule other) {
        return
            atOptimalTime.equals(other.atOptimalTime) &&

            inLocalTime.equals(other.inLocalTime) &&

            time.equals(other.time)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.atOptimalTime,
                   this.inLocalTime,
                   this.time
               );
    }

    @Override
    public String toString() {
        return "CanvasTriggerScheduleCreateCreateBodySchedule{" +
               "atOptimalTime=" + atOptimalTime +
               "inLocalTime=" + inLocalTime +
               "time=" + time +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> atOptimalTime = Optional.empty();
        private Optional<Boolean> inLocalTime = Optional.empty();
        private Optional<String> time = Optional.empty();

        private Builder() {}

        public Builder from(CanvasTriggerScheduleCreateCreateBodySchedule other) {
            atOptimalTime(other.getAtOptimalTime());
            inLocalTime(other.getInLocalTime());
            time(other.getTime());
            return this;
        }

        /**
         * Sets value for `atOptimalTime`
         */
        @JsonSetter("at_optimal_time")
        public Builder atOptimalTime(Boolean atOptimalTime) {
            this.atOptimalTime = Optional.ofNullable(atOptimalTime);

            return this;
        }

        public Builder atOptimalTime(Optional<Boolean> atOptimalTime) {
            this.atOptimalTime = atOptimalTime;
            return this;
        }

        /**
         * Sets value for `inLocalTime`
         */
        @JsonSetter("in_local_time")
        public Builder inLocalTime(Boolean inLocalTime) {
            this.inLocalTime = Optional.ofNullable(inLocalTime);

            return this;
        }

        public Builder inLocalTime(Optional<Boolean> inLocalTime) {
            this.inLocalTime = inLocalTime;
            return this;
        }

        /**
         * Sets value for `time`
         */
        @JsonSetter("time")
        public Builder time(String time) {
            this.time = Optional.ofNullable(time);

            return this;
        }

        public Builder time(Optional<String> time) {
            this.time = time;
            return this;
        }


        public CanvasTriggerScheduleCreateCreateBodySchedule build() {
            return new CanvasTriggerScheduleCreateCreateBodySchedule(
                       atOptimalTime,
                       inLocalTime,
                       time
                   );
        }
    }

}



