
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * CanvasTriggerSendCreateBodyRecipientsItemAttributes
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CanvasTriggerSendCreateBodyRecipientsItemAttributes.Builder.class)
public final class CanvasTriggerSendCreateBodyRecipientsItemAttributes {
    private final Optional<String> firstName;

    private CanvasTriggerSendCreateBodyRecipientsItemAttributes(
        Optional<String> firstName
    ) {
        this.firstName = firstName;
    }

    /**
     * Retrieves value for `firstName`
     */
    @JsonProperty("first_name")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getFirstName() {
        return firstName.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof CanvasTriggerSendCreateBodyRecipientsItemAttributes &&
               equalTo((CanvasTriggerSendCreateBodyRecipientsItemAttributes) other);
    }

    private boolean equalTo(CanvasTriggerSendCreateBodyRecipientsItemAttributes other) {
        return
            firstName.equals(other.firstName)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.firstName
               );
    }

    @Override
    public String toString() {
        return "CanvasTriggerSendCreateBodyRecipientsItemAttributes{" +
               "firstName=" + firstName +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> firstName = Optional.empty();

        private Builder() {}

        public Builder from(CanvasTriggerSendCreateBodyRecipientsItemAttributes other) {
            firstName(other.getFirstName());
            return this;
        }

        /**
         * Sets value for `firstName`
         */
        @JsonSetter("first_name")
        public Builder firstName(String firstName) {
            this.firstName = Optional.ofNullable(firstName);

            return this;
        }

        public Builder firstName(Optional<String> firstName) {
            this.firstName = firstName;
            return this;
        }


        public CanvasTriggerSendCreateBodyRecipientsItemAttributes build() {
            return new CanvasTriggerSendCreateBodyRecipientsItemAttributes(
                       firstName
                   );
        }
    }

}



