
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * CanvasTriggerScheduleCreateCreateBodyRecipientsItem
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CanvasTriggerScheduleCreateCreateBodyRecipientsItem.Builder.class)
public final class CanvasTriggerScheduleCreateCreateBodyRecipientsItem {
    private final Optional<Map<?, ?>> canvasEntryProperties;
    private final Optional<String> externalUserId;
    private final Optional<Map<?, ?>> triggerProperties;
    private final Optional<String> userAlias;

    private CanvasTriggerScheduleCreateCreateBodyRecipientsItem(
        Optional<Map<?, ?>> canvasEntryProperties,
        Optional<String> externalUserId,
        Optional<Map<?, ?>> triggerProperties,
        Optional<String> userAlias
    ) {
        this.canvasEntryProperties = canvasEntryProperties;
        this.externalUserId = externalUserId;
        this.triggerProperties = triggerProperties;
        this.userAlias = userAlias;
    }

    /**
     * Retrieves value for `canvasEntryProperties`
     */
    @JsonProperty("canvas_entry_properties")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Map<?, ?> getCanvasEntryProperties() {
        return canvasEntryProperties.orElse(null);
    }

    /**
     * Retrieves value for `externalUserId`
     */
    @JsonProperty("external_user_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getExternalUserId() {
        return externalUserId.orElse(null);
    }

    /**
     * Retrieves value for `triggerProperties`
     */
    @JsonProperty("trigger_properties")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Map<?, ?> getTriggerProperties() {
        return triggerProperties.orElse(null);
    }

    /**
     * Retrieves value for `userAlias`
     */
    @JsonProperty("user_alias")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getUserAlias() {
        return userAlias.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof CanvasTriggerScheduleCreateCreateBodyRecipientsItem &&
               equalTo((CanvasTriggerScheduleCreateCreateBodyRecipientsItem) other);
    }

    private boolean equalTo(CanvasTriggerScheduleCreateCreateBodyRecipientsItem other) {
        return
            canvasEntryProperties.equals(other.canvasEntryProperties) &&

            externalUserId.equals(other.externalUserId) &&

            triggerProperties.equals(other.triggerProperties) &&

            userAlias.equals(other.userAlias)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.canvasEntryProperties,
                   this.externalUserId,
                   this.triggerProperties,
                   this.userAlias
               );
    }

    @Override
    public String toString() {
        return "CanvasTriggerScheduleCreateCreateBodyRecipientsItem{" +
               "canvasEntryProperties=" + canvasEntryProperties +
               "externalUserId=" + externalUserId +
               "triggerProperties=" + triggerProperties +
               "userAlias=" + userAlias +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Map<?, ?>> canvasEntryProperties = Optional.empty();
        private Optional<String> externalUserId = Optional.empty();
        private Optional<Map<?, ?>> triggerProperties = Optional.empty();
        private Optional<String> userAlias = Optional.empty();

        private Builder() {}

        public Builder from(CanvasTriggerScheduleCreateCreateBodyRecipientsItem other) {
            canvasEntryProperties(other.getCanvasEntryProperties());
            externalUserId(other.getExternalUserId());
            triggerProperties(other.getTriggerProperties());
            userAlias(other.getUserAlias());
            return this;
        }

        /**
         * Sets value for `canvasEntryProperties`
         */
        @JsonSetter("canvas_entry_properties")
        public Builder canvasEntryProperties(Map<?, ?> canvasEntryProperties) {
            this.canvasEntryProperties = Optional.ofNullable(canvasEntryProperties);

            return this;
        }

        public Builder canvasEntryProperties(Optional<Map<?, ?>> canvasEntryProperties) {
            this.canvasEntryProperties = canvasEntryProperties;
            return this;
        }

        /**
         * Sets value for `externalUserId`
         */
        @JsonSetter("external_user_id")
        public Builder externalUserId(String externalUserId) {
            this.externalUserId = Optional.ofNullable(externalUserId);

            return this;
        }

        public Builder externalUserId(Optional<String> externalUserId) {
            this.externalUserId = externalUserId;
            return this;
        }

        /**
         * Sets value for `triggerProperties`
         */
        @JsonSetter("trigger_properties")
        public Builder triggerProperties(Map<?, ?> triggerProperties) {
            this.triggerProperties = Optional.ofNullable(triggerProperties);

            return this;
        }

        public Builder triggerProperties(Optional<Map<?, ?>> triggerProperties) {
            this.triggerProperties = triggerProperties;
            return this;
        }

        /**
         * Sets value for `userAlias`
         */
        @JsonSetter("user_alias")
        public Builder userAlias(String userAlias) {
            this.userAlias = Optional.ofNullable(userAlias);

            return this;
        }

        public Builder userAlias(Optional<String> userAlias) {
            this.userAlias = userAlias;
            return this;
        }


        public CanvasTriggerScheduleCreateCreateBodyRecipientsItem build() {
            return new CanvasTriggerScheduleCreateCreateBodyRecipientsItem(
                       canvasEntryProperties,
                       externalUserId,
                       triggerProperties,
                       userAlias
                   );
        }
    }

}



