
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * CanvasTriggerSendCreateBodyRecipientsItem
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CanvasTriggerSendCreateBodyRecipientsItem.Builder.class)
public final class CanvasTriggerSendCreateBodyRecipientsItem {
    private final Optional<CanvasTriggerSendCreateBodyRecipientsItemAttributes> attributes;
    private final Optional<String> canvasEntryProperties;
    private final Optional<String> externalUserId;
    private final Optional<Boolean> sendToExistingOnly;
    private final Optional<Map<?, ?>> triggerProperties;
    private final Optional<CanvasTriggerSendCreateBodyRecipientsItemUserAlias> userAlias;

    private CanvasTriggerSendCreateBodyRecipientsItem(
        Optional<CanvasTriggerSendCreateBodyRecipientsItemAttributes> attributes,
        Optional<String> canvasEntryProperties,
        Optional<String> externalUserId,
        Optional<Boolean> sendToExistingOnly,
        Optional<Map<?, ?>> triggerProperties,
        Optional<CanvasTriggerSendCreateBodyRecipientsItemUserAlias> userAlias
    ) {
        this.attributes = attributes;
        this.canvasEntryProperties = canvasEntryProperties;
        this.externalUserId = externalUserId;
        this.sendToExistingOnly = sendToExistingOnly;
        this.triggerProperties = triggerProperties;
        this.userAlias = userAlias;
    }

    /**
     * Retrieves value for `attributes`
     */
    @JsonProperty("attributes")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public CanvasTriggerSendCreateBodyRecipientsItemAttributes getAttributes() {
        return attributes.orElse(null);
    }

    /**
     * Retrieves value for `canvasEntryProperties`
     */
    @JsonProperty("canvas_entry_properties")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getCanvasEntryProperties() {
        return canvasEntryProperties.orElse(null);
    }

    /**
     * Retrieves value for `externalUserId`
     */
    @JsonProperty("external_user_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getExternalUserId() {
        return externalUserId.orElse(null);
    }

    /**
     * Retrieves value for `sendToExistingOnly`
     */
    @JsonProperty("send_to_existing_only")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Boolean getSendToExistingOnly() {
        return sendToExistingOnly.orElse(null);
    }

    /**
     * Retrieves value for `triggerProperties`
     */
    @JsonProperty("trigger_properties")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Map<?, ?> getTriggerProperties() {
        return triggerProperties.orElse(null);
    }

    /**
     * Retrieves value for `userAlias`
     */
    @JsonProperty("user_alias")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public CanvasTriggerSendCreateBodyRecipientsItemUserAlias getUserAlias() {
        return userAlias.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof CanvasTriggerSendCreateBodyRecipientsItem &&
               equalTo((CanvasTriggerSendCreateBodyRecipientsItem) other);
    }

    private boolean equalTo(CanvasTriggerSendCreateBodyRecipientsItem other) {
        return
            attributes.equals(other.attributes) &&

            canvasEntryProperties.equals(other.canvasEntryProperties) &&

            externalUserId.equals(other.externalUserId) &&

            sendToExistingOnly.equals(other.sendToExistingOnly) &&

            triggerProperties.equals(other.triggerProperties) &&

            userAlias.equals(other.userAlias)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.attributes,
                   this.canvasEntryProperties,
                   this.externalUserId,
                   this.sendToExistingOnly,
                   this.triggerProperties,
                   this.userAlias
               );
    }

    @Override
    public String toString() {
        return "CanvasTriggerSendCreateBodyRecipientsItem{" +
               "attributes=" + attributes +
               "canvasEntryProperties=" + canvasEntryProperties +
               "externalUserId=" + externalUserId +
               "sendToExistingOnly=" + sendToExistingOnly +
               "triggerProperties=" + triggerProperties +
               "userAlias=" + userAlias +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<CanvasTriggerSendCreateBodyRecipientsItemAttributes> attributes = Optional.empty();
        private Optional<String> canvasEntryProperties = Optional.empty();
        private Optional<String> externalUserId = Optional.empty();
        private Optional<Boolean> sendToExistingOnly = Optional.empty();
        private Optional<Map<?, ?>> triggerProperties = Optional.empty();
        private Optional<CanvasTriggerSendCreateBodyRecipientsItemUserAlias> userAlias = Optional.empty();

        private Builder() {}

        public Builder from(CanvasTriggerSendCreateBodyRecipientsItem other) {
            attributes(other.getAttributes());
            canvasEntryProperties(other.getCanvasEntryProperties());
            externalUserId(other.getExternalUserId());
            sendToExistingOnly(other.getSendToExistingOnly());
            triggerProperties(other.getTriggerProperties());
            userAlias(other.getUserAlias());
            return this;
        }

        /**
         * Sets value for `attributes`
         */
        @JsonSetter("attributes")
        public Builder attributes(CanvasTriggerSendCreateBodyRecipientsItemAttributes attributes) {
            this.attributes = Optional.ofNullable(attributes);

            return this;
        }

        public Builder attributes(Optional<CanvasTriggerSendCreateBodyRecipientsItemAttributes>
                                  attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Sets value for `canvasEntryProperties`
         */
        @JsonSetter("canvas_entry_properties")
        public Builder canvasEntryProperties(String canvasEntryProperties) {
            this.canvasEntryProperties = Optional.ofNullable(canvasEntryProperties);

            return this;
        }

        public Builder canvasEntryProperties(Optional<String> canvasEntryProperties) {
            this.canvasEntryProperties = canvasEntryProperties;
            return this;
        }

        /**
         * Sets value for `externalUserId`
         */
        @JsonSetter("external_user_id")
        public Builder externalUserId(String externalUserId) {
            this.externalUserId = Optional.ofNullable(externalUserId);

            return this;
        }

        public Builder externalUserId(Optional<String> externalUserId) {
            this.externalUserId = externalUserId;
            return this;
        }

        /**
         * Sets value for `sendToExistingOnly`
         */
        @JsonSetter("send_to_existing_only")
        public Builder sendToExistingOnly(Boolean sendToExistingOnly) {
            this.sendToExistingOnly = Optional.ofNullable(sendToExistingOnly);

            return this;
        }

        public Builder sendToExistingOnly(Optional<Boolean> sendToExistingOnly) {
            this.sendToExistingOnly = sendToExistingOnly;
            return this;
        }

        /**
         * Sets value for `triggerProperties`
         */
        @JsonSetter("trigger_properties")
        public Builder triggerProperties(Map<?, ?> triggerProperties) {
            this.triggerProperties = Optional.ofNullable(triggerProperties);

            return this;
        }

        public Builder triggerProperties(Optional<Map<?, ?>> triggerProperties) {
            this.triggerProperties = triggerProperties;
            return this;
        }

        /**
         * Sets value for `userAlias`
         */
        @JsonSetter("user_alias")
        public Builder userAlias(CanvasTriggerSendCreateBodyRecipientsItemUserAlias userAlias) {
            this.userAlias = Optional.ofNullable(userAlias);

            return this;
        }

        public Builder userAlias(Optional<CanvasTriggerSendCreateBodyRecipientsItemUserAlias> userAlias) {
            this.userAlias = userAlias;
            return this;
        }


        public CanvasTriggerSendCreateBodyRecipientsItem build() {
            return new CanvasTriggerSendCreateBodyRecipientsItem(
                       attributes,
                       canvasEntryProperties,
                       externalUserId,
                       sendToExistingOnly,
                       triggerProperties,
                       userAlias
                   );
        }
    }

}



