
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * CanvasTriggerScheduleDeleteCreateBody
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CanvasTriggerScheduleDeleteCreateBody.Builder.class)
public final class CanvasTriggerScheduleDeleteCreateBody {
    private final Optional<String> canvasId;
    private final Optional<String> scheduleId;

    private CanvasTriggerScheduleDeleteCreateBody(
        Optional<String> canvasId,
        Optional<String> scheduleId
    ) {
        this.canvasId = canvasId;
        this.scheduleId = scheduleId;
    }

    /**
     * Retrieves value for `canvasId`
     */
    @JsonProperty("canvas_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getCanvasId() {
        return canvasId.orElse(null);
    }

    /**
     * Retrieves value for `scheduleId`
     */
    @JsonProperty("schedule_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getScheduleId() {
        return scheduleId.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof CanvasTriggerScheduleDeleteCreateBody &&
               equalTo((CanvasTriggerScheduleDeleteCreateBody) other);
    }

    private boolean equalTo(CanvasTriggerScheduleDeleteCreateBody other) {
        return
            canvasId.equals(other.canvasId) &&

            scheduleId.equals(other.scheduleId)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.canvasId,
                   this.scheduleId
               );
    }

    @Override
    public String toString() {
        return "CanvasTriggerScheduleDeleteCreateBody{" +
               "canvasId=" + canvasId +
               "scheduleId=" + scheduleId +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> canvasId = Optional.empty();
        private Optional<String> scheduleId = Optional.empty();

        private Builder() {}

        public Builder from(CanvasTriggerScheduleDeleteCreateBody other) {
            canvasId(other.getCanvasId());
            scheduleId(other.getScheduleId());
            return this;
        }

        /**
         * Sets value for `canvasId`
         */
        @JsonSetter("canvas_id")
        public Builder canvasId(String canvasId) {
            this.canvasId = Optional.ofNullable(canvasId);

            return this;
        }

        public Builder canvasId(Optional<String> canvasId) {
            this.canvasId = canvasId;
            return this;
        }

        /**
         * Sets value for `scheduleId`
         */
        @JsonSetter("schedule_id")
        public Builder scheduleId(String scheduleId) {
            this.scheduleId = Optional.ofNullable(scheduleId);

            return this;
        }

        public Builder scheduleId(Optional<String> scheduleId) {
            this.scheduleId = scheduleId;
            return this;
        }


        public CanvasTriggerScheduleDeleteCreateBody build() {
            return new CanvasTriggerScheduleDeleteCreateBody(
                       canvasId,
                       scheduleId
                   );
        }
    }

}



