
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * CatalogsItemsUpdateBody
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CatalogsItemsUpdateBody.Builder.class)
public final class CatalogsItemsUpdateBody {
    private final Optional<List<Map<?, ?>>> items;

    private CatalogsItemsUpdateBody(
        Optional<List<Map<?, ?>>> items
    ) {
        this.items = items;
    }

    /**
     * Retrieves value for `items`
     */
    @JsonProperty("items")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public List<Map<?, ?>> getItems() {
        return items.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof CatalogsItemsUpdateBody && equalTo((CatalogsItemsUpdateBody) other);
    }

    private boolean equalTo(CatalogsItemsUpdateBody other) {
        return
            items.equals(other.items)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.items
               );
    }

    @Override
    public String toString() {
        return "CatalogsItemsUpdateBody{" +
               "items=" + items +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<Map<?, ?>>> items = Optional.empty();

        private Builder() {}

        public Builder from(CatalogsItemsUpdateBody other) {
            items(other.getItems());
            return this;
        }

        /**
         * Sets value for `items`
         */
        @JsonSetter("items")
        public Builder items(List<Map<?, ?>> items) {
            this.items = Optional.ofNullable(items);

            return this;
        }

        public Builder items(Optional<List<Map<?, ?>>> items) {
            this.items = items;
            return this;
        }


        public CatalogsItemsUpdateBody build() {
            return new CatalogsItemsUpdateBody(
                       items
                   );
        }
    }

}



