
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * MessagesScheduleUpdateCreateBodyMessagesApplePush
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MessagesScheduleUpdateCreateBodyMessagesApplePush.Builder.class)
public final class MessagesScheduleUpdateCreateBodyMessagesApplePush {
    private final Optional<String> alert;
    private final Optional<Integer> badge;

    private MessagesScheduleUpdateCreateBodyMessagesApplePush(
        Optional<String> alert,
        Optional<Integer> badge
    ) {
        this.alert = alert;
        this.badge = badge;
    }

    /**
     * Retrieves value for `alert`
     */
    @JsonProperty("alert")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getAlert() {
        return alert.orElse(null);
    }

    /**
     * Retrieves value for `badge`
     */
    @JsonProperty("badge")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Integer getBadge() {
        return badge.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof MessagesScheduleUpdateCreateBodyMessagesApplePush &&
               equalTo((MessagesScheduleUpdateCreateBodyMessagesApplePush) other);
    }

    private boolean equalTo(MessagesScheduleUpdateCreateBodyMessagesApplePush other) {
        return
            alert.equals(other.alert) &&

            badge.equals(other.badge)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.alert,
                   this.badge
               );
    }

    @Override
    public String toString() {
        return "MessagesScheduleUpdateCreateBodyMessagesApplePush{" +
               "alert=" + alert +
               "badge=" + badge +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> alert = Optional.empty();
        private Optional<Integer> badge = Optional.empty();

        private Builder() {}

        public Builder from(MessagesScheduleUpdateCreateBodyMessagesApplePush other) {
            alert(other.getAlert());
            badge(other.getBadge());
            return this;
        }

        /**
         * Sets value for `alert`
         */
        @JsonSetter("alert")
        public Builder alert(String alert) {
            this.alert = Optional.ofNullable(alert);

            return this;
        }

        public Builder alert(Optional<String> alert) {
            this.alert = alert;
            return this;
        }

        /**
         * Sets value for `badge`
         */
        @JsonSetter("badge")
        public Builder badge(Integer badge) {
            this.badge = Optional.ofNullable(badge);

            return this;
        }

        public Builder badge(Optional<Integer> badge) {
            this.badge = badge;
            return this;
        }


        public MessagesScheduleUpdateCreateBodyMessagesApplePush build() {
            return new MessagesScheduleUpdateCreateBodyMessagesApplePush(
                       alert,
                       badge
                   );
        }
    }

}



