
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * MessagesSendCreateBodyAudience
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MessagesSendCreateBodyAudience.Builder.class)
public final class MessagesSendCreateBodyAudience {
    private final Optional<List<Map<?, ?>>> and;

    private MessagesSendCreateBodyAudience(
        Optional<List<Map<?, ?>>> and
    ) {
        this.and = and;
    }

    /**
     * Retrieves value for `and`
     */
    @JsonProperty("AND")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public List<Map<?, ?>> getAnd() {
        return and.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof MessagesSendCreateBodyAudience &&
               equalTo((MessagesSendCreateBodyAudience) other);
    }

    private boolean equalTo(MessagesSendCreateBodyAudience other) {
        return
            and.equals(other.and)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.and
               );
    }

    @Override
    public String toString() {
        return "MessagesSendCreateBodyAudience{" +
               "and=" + and +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<Map<?, ?>>> and = Optional.empty();

        private Builder() {}

        public Builder from(MessagesSendCreateBodyAudience other) {
            and (other.getAnd());
            return this;
        }

        /**
         * Sets value for `and`
         */
        @JsonSetter("AND")
        public Builder and (List<Map<?, ?>> and) {
            this.and = Optional.ofNullable( and);

            return this;
        }

        public Builder and (Optional<List<Map<?, ?>>> and) {
            this.and = and;
            return this;
        }


        public MessagesSendCreateBodyAudience build() {
            return new MessagesSendCreateBodyAudience(
                       and
                   );
        }
    }

}



