
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * MessagesSendCreateBody
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MessagesSendCreateBody.Builder.class)
public final class MessagesSendCreateBody {
    private final Optional<MessagesSendCreateBodyAudience> audience;
    private final Optional<String> broadcast;
    private final Optional<String> campaignId;
    private final Optional<String> externalUserIds;
    private final Optional<MessagesSendCreateBodyMessages> messages;
    private final Optional<String> overrideFrequencyCapping;
    private final Optional<String> recipientSubscriptionState;
    private final Optional<String> segmentId;
    private final Optional<String> sendId;
    private final Optional<MessagesSendCreateBodyUserAliases> userAliases;

    private MessagesSendCreateBody(
        Optional<MessagesSendCreateBodyAudience> audience,
        Optional<String> broadcast,
        Optional<String> campaignId,
        Optional<String> externalUserIds,
        Optional<MessagesSendCreateBodyMessages> messages,
        Optional<String> overrideFrequencyCapping,
        Optional<String> recipientSubscriptionState,
        Optional<String> segmentId,
        Optional<String> sendId,
        Optional<MessagesSendCreateBodyUserAliases> userAliases
    ) {
        this.audience = audience;
        this.broadcast = broadcast;
        this.campaignId = campaignId;
        this.externalUserIds = externalUserIds;
        this.messages = messages;
        this.overrideFrequencyCapping = overrideFrequencyCapping;
        this.recipientSubscriptionState = recipientSubscriptionState;
        this.segmentId = segmentId;
        this.sendId = sendId;
        this.userAliases = userAliases;
    }

    /**
     * Retrieves value for `audience`
     */
    @JsonProperty("audience")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public MessagesSendCreateBodyAudience getAudience() {
        return audience.orElse(null);
    }

    /**
     * Retrieves value for `broadcast`
     */
    @JsonProperty("broadcast")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getBroadcast() {
        return broadcast.orElse(null);
    }

    /**
     * Retrieves value for `campaignId`
     */
    @JsonProperty("campaign_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getCampaignId() {
        return campaignId.orElse(null);
    }

    /**
     * Retrieves value for `externalUserIds`
     */
    @JsonProperty("external_user_ids")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getExternalUserIds() {
        return externalUserIds.orElse(null);
    }

    /**
     * Retrieves value for `messages`
     */
    @JsonProperty("messages")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public MessagesSendCreateBodyMessages getMessages() {
        return messages.orElse(null);
    }

    /**
     * Retrieves value for `overrideFrequencyCapping`
     */
    @JsonProperty("override_frequency_capping")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getOverrideFrequencyCapping() {
        return overrideFrequencyCapping.orElse(null);
    }

    /**
     * Retrieves value for `recipientSubscriptionState`
     */
    @JsonProperty("recipient_subscription_state")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getRecipientSubscriptionState() {
        return recipientSubscriptionState.orElse(null);
    }

    /**
     * Retrieves value for `segmentId`
     */
    @JsonProperty("segment_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getSegmentId() {
        return segmentId.orElse(null);
    }

    /**
     * Retrieves value for `sendId`
     */
    @JsonProperty("send_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getSendId() {
        return sendId.orElse(null);
    }

    /**
     * Retrieves value for `userAliases`
     */
    @JsonProperty("user_aliases")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public MessagesSendCreateBodyUserAliases getUserAliases() {
        return userAliases.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof MessagesSendCreateBody && equalTo((MessagesSendCreateBody) other);
    }

    private boolean equalTo(MessagesSendCreateBody other) {
        return
            audience.equals(other.audience) &&

            broadcast.equals(other.broadcast) &&

            campaignId.equals(other.campaignId) &&

            externalUserIds.equals(other.externalUserIds) &&

            messages.equals(other.messages) &&

            overrideFrequencyCapping.equals(other.overrideFrequencyCapping) &&

            recipientSubscriptionState.equals(other.recipientSubscriptionState) &&

            segmentId.equals(other.segmentId) &&

            sendId.equals(other.sendId) &&

            userAliases.equals(other.userAliases)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.audience,
                   this.broadcast,
                   this.campaignId,
                   this.externalUserIds,
                   this.messages,
                   this.overrideFrequencyCapping,
                   this.recipientSubscriptionState,
                   this.segmentId,
                   this.sendId,
                   this.userAliases
               );
    }

    @Override
    public String toString() {
        return "MessagesSendCreateBody{" +
               "audience=" + audience +
               "broadcast=" + broadcast +
               "campaignId=" + campaignId +
               "externalUserIds=" + externalUserIds +
               "messages=" + messages +
               "overrideFrequencyCapping=" + overrideFrequencyCapping +
               "recipientSubscriptionState=" + recipientSubscriptionState +
               "segmentId=" + segmentId +
               "sendId=" + sendId +
               "userAliases=" + userAliases +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<MessagesSendCreateBodyAudience> audience = Optional.empty();
        private Optional<String> broadcast = Optional.empty();
        private Optional<String> campaignId = Optional.empty();
        private Optional<String> externalUserIds = Optional.empty();
        private Optional<MessagesSendCreateBodyMessages> messages = Optional.empty();
        private Optional<String> overrideFrequencyCapping = Optional.empty();
        private Optional<String> recipientSubscriptionState = Optional.empty();
        private Optional<String> segmentId = Optional.empty();
        private Optional<String> sendId = Optional.empty();
        private Optional<MessagesSendCreateBodyUserAliases> userAliases = Optional.empty();

        private Builder() {}

        public Builder from(MessagesSendCreateBody other) {
            audience(other.getAudience());
            broadcast(other.getBroadcast());
            campaignId(other.getCampaignId());
            externalUserIds(other.getExternalUserIds());
            messages(other.getMessages());
            overrideFrequencyCapping(other.getOverrideFrequencyCapping());
            recipientSubscriptionState(other.getRecipientSubscriptionState());
            segmentId(other.getSegmentId());
            sendId(other.getSendId());
            userAliases(other.getUserAliases());
            return this;
        }

        /**
         * Sets value for `audience`
         */
        @JsonSetter("audience")
        public Builder audience(MessagesSendCreateBodyAudience audience) {
            this.audience = Optional.ofNullable(audience);

            return this;
        }

        public Builder audience(Optional<MessagesSendCreateBodyAudience> audience) {
            this.audience = audience;
            return this;
        }

        /**
         * Sets value for `broadcast`
         */
        @JsonSetter("broadcast")
        public Builder broadcast(String broadcast) {
            this.broadcast = Optional.ofNullable(broadcast);

            return this;
        }

        public Builder broadcast(Optional<String> broadcast) {
            this.broadcast = broadcast;
            return this;
        }

        /**
         * Sets value for `campaignId`
         */
        @JsonSetter("campaign_id")
        public Builder campaignId(String campaignId) {
            this.campaignId = Optional.ofNullable(campaignId);

            return this;
        }

        public Builder campaignId(Optional<String> campaignId) {
            this.campaignId = campaignId;
            return this;
        }

        /**
         * Sets value for `externalUserIds`
         */
        @JsonSetter("external_user_ids")
        public Builder externalUserIds(String externalUserIds) {
            this.externalUserIds = Optional.ofNullable(externalUserIds);

            return this;
        }

        public Builder externalUserIds(Optional<String> externalUserIds) {
            this.externalUserIds = externalUserIds;
            return this;
        }

        /**
         * Sets value for `messages`
         */
        @JsonSetter("messages")
        public Builder messages(MessagesSendCreateBodyMessages messages) {
            this.messages = Optional.ofNullable(messages);

            return this;
        }

        public Builder messages(Optional<MessagesSendCreateBodyMessages> messages) {
            this.messages = messages;
            return this;
        }

        /**
         * Sets value for `overrideFrequencyCapping`
         */
        @JsonSetter("override_frequency_capping")
        public Builder overrideFrequencyCapping(String overrideFrequencyCapping) {
            this.overrideFrequencyCapping = Optional.ofNullable(overrideFrequencyCapping);

            return this;
        }

        public Builder overrideFrequencyCapping(Optional<String> overrideFrequencyCapping) {
            this.overrideFrequencyCapping = overrideFrequencyCapping;
            return this;
        }

        /**
         * Sets value for `recipientSubscriptionState`
         */
        @JsonSetter("recipient_subscription_state")
        public Builder recipientSubscriptionState(String recipientSubscriptionState) {
            this.recipientSubscriptionState = Optional.ofNullable(recipientSubscriptionState);

            return this;
        }

        public Builder recipientSubscriptionState(Optional<String> recipientSubscriptionState) {
            this.recipientSubscriptionState = recipientSubscriptionState;
            return this;
        }

        /**
         * Sets value for `segmentId`
         */
        @JsonSetter("segment_id")
        public Builder segmentId(String segmentId) {
            this.segmentId = Optional.ofNullable(segmentId);

            return this;
        }

        public Builder segmentId(Optional<String> segmentId) {
            this.segmentId = segmentId;
            return this;
        }

        /**
         * Sets value for `sendId`
         */
        @JsonSetter("send_id")
        public Builder sendId(String sendId) {
            this.sendId = Optional.ofNullable(sendId);

            return this;
        }

        public Builder sendId(Optional<String> sendId) {
            this.sendId = sendId;
            return this;
        }

        /**
         * Sets value for `userAliases`
         */
        @JsonSetter("user_aliases")
        public Builder userAliases(MessagesSendCreateBodyUserAliases userAliases) {
            this.userAliases = Optional.ofNullable(userAliases);

            return this;
        }

        public Builder userAliases(Optional<MessagesSendCreateBodyUserAliases> userAliases) {
            this.userAliases = userAliases;
            return this;
        }


        public MessagesSendCreateBody build() {
            return new MessagesSendCreateBody(
                       audience,
                       broadcast,
                       campaignId,
                       externalUserIds,
                       messages,
                       overrideFrequencyCapping,
                       recipientSubscriptionState,
                       segmentId,
                       sendId,
                       userAliases
                   );
        }
    }

}



