
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * MessagesScheduleDeleteCreateBody
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MessagesScheduleDeleteCreateBody.Builder.class)
public final class MessagesScheduleDeleteCreateBody {
    private final Optional<String> scheduleId;

    private MessagesScheduleDeleteCreateBody(
        Optional<String> scheduleId
    ) {
        this.scheduleId = scheduleId;
    }

    /**
     * Retrieves value for `scheduleId`
     */
    @JsonProperty("schedule_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getScheduleId() {
        return scheduleId.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof MessagesScheduleDeleteCreateBody &&
               equalTo((MessagesScheduleDeleteCreateBody) other);
    }

    private boolean equalTo(MessagesScheduleDeleteCreateBody other) {
        return
            scheduleId.equals(other.scheduleId)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.scheduleId
               );
    }

    @Override
    public String toString() {
        return "MessagesScheduleDeleteCreateBody{" +
               "scheduleId=" + scheduleId +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> scheduleId = Optional.empty();

        private Builder() {}

        public Builder from(MessagesScheduleDeleteCreateBody other) {
            scheduleId(other.getScheduleId());
            return this;
        }

        /**
         * Sets value for `scheduleId`
         */
        @JsonSetter("schedule_id")
        public Builder scheduleId(String scheduleId) {
            this.scheduleId = Optional.ofNullable(scheduleId);

            return this;
        }

        public Builder scheduleId(Optional<String> scheduleId) {
            this.scheduleId = scheduleId;
            return this;
        }


        public MessagesScheduleDeleteCreateBody build() {
            return new MessagesScheduleDeleteCreateBody(
                       scheduleId
                   );
        }
    }

}



