
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * PreferenceCenterV1UpdateBodyTriggerProperties
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PreferenceCenterV1UpdateBodyTriggerProperties.Builder.class)
public final class PreferenceCenterV1UpdateBodyTriggerProperties {
    private final Optional<String> exampleIntegerProperty;
    private final Optional<String> exampleStringProperty;

    private PreferenceCenterV1UpdateBodyTriggerProperties(
        Optional<String> exampleIntegerProperty,
        Optional<String> exampleStringProperty
    ) {
        this.exampleIntegerProperty = exampleIntegerProperty;
        this.exampleStringProperty = exampleStringProperty;
    }

    /**
     * Retrieves value for `exampleIntegerProperty`
     */
    @JsonProperty("example_integer_property")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getExampleIntegerProperty() {
        return exampleIntegerProperty.orElse(null);
    }

    /**
     * Retrieves value for `exampleStringProperty`
     */
    @JsonProperty("example_string_property")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getExampleStringProperty() {
        return exampleStringProperty.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof PreferenceCenterV1UpdateBodyTriggerProperties &&
               equalTo((PreferenceCenterV1UpdateBodyTriggerProperties) other);
    }

    private boolean equalTo(PreferenceCenterV1UpdateBodyTriggerProperties other) {
        return
            exampleIntegerProperty.equals(other.exampleIntegerProperty) &&

            exampleStringProperty.equals(other.exampleStringProperty)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.exampleIntegerProperty,
                   this.exampleStringProperty
               );
    }

    @Override
    public String toString() {
        return "PreferenceCenterV1UpdateBodyTriggerProperties{" +
               "exampleIntegerProperty=" + exampleIntegerProperty +
               "exampleStringProperty=" + exampleStringProperty +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> exampleIntegerProperty = Optional.empty();
        private Optional<String> exampleStringProperty = Optional.empty();

        private Builder() {}

        public Builder from(PreferenceCenterV1UpdateBodyTriggerProperties other) {
            exampleIntegerProperty(other.getExampleIntegerProperty());
            exampleStringProperty(other.getExampleStringProperty());
            return this;
        }

        /**
         * Sets value for `exampleIntegerProperty`
         */
        @JsonSetter("example_integer_property")
        public Builder exampleIntegerProperty(String exampleIntegerProperty) {
            this.exampleIntegerProperty = Optional.ofNullable(exampleIntegerProperty);

            return this;
        }

        public Builder exampleIntegerProperty(Optional<String> exampleIntegerProperty) {
            this.exampleIntegerProperty = exampleIntegerProperty;
            return this;
        }

        /**
         * Sets value for `exampleStringProperty`
         */
        @JsonSetter("example_string_property")
        public Builder exampleStringProperty(String exampleStringProperty) {
            this.exampleStringProperty = Optional.ofNullable(exampleStringProperty);

            return this;
        }

        public Builder exampleStringProperty(Optional<String> exampleStringProperty) {
            this.exampleStringProperty = exampleStringProperty;
            return this;
        }


        public PreferenceCenterV1UpdateBodyTriggerProperties build() {
            return new PreferenceCenterV1UpdateBodyTriggerProperties(
                       exampleIntegerProperty,
                       exampleStringProperty
                   );
        }
    }

}



