
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.List;
import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * ScimV2UsersUpdateBody
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ScimV2UsersUpdateBody.Builder.class)
public final class ScimV2UsersUpdateBody {
    private final Optional<String> department;
    private final Optional<ScimV2UsersUpdateBodyName> name;
    private final Optional<ScimV2UsersUpdateBodyPermissions> permissions;
    private final Optional<List<String>> schemas;

    private ScimV2UsersUpdateBody(
        Optional<String> department,
        Optional<ScimV2UsersUpdateBodyName> name,
        Optional<ScimV2UsersUpdateBodyPermissions> permissions,
        Optional<List<String>> schemas
    ) {
        this.department = department;
        this.name = name;
        this.permissions = permissions;
        this.schemas = schemas;
    }

    /**
     * Retrieves value for `department`
     */
    @JsonProperty("department")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getDepartment() {
        return department.orElse(null);
    }

    /**
     * Retrieves value for `name`
     */
    @JsonProperty("name")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public ScimV2UsersUpdateBodyName getName() {
        return name.orElse(null);
    }

    /**
     * Retrieves value for `permissions`
     */
    @JsonProperty("permissions")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public ScimV2UsersUpdateBodyPermissions getPermissions() {
        return permissions.orElse(null);
    }

    /**
     * Retrieves value for `schemas`
     */
    @JsonProperty("schemas")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public List<String> getSchemas() {
        return schemas.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof ScimV2UsersUpdateBody && equalTo((ScimV2UsersUpdateBody) other);
    }

    private boolean equalTo(ScimV2UsersUpdateBody other) {
        return
            department.equals(other.department) &&

            name.equals(other.name) &&

            permissions.equals(other.permissions) &&

            schemas.equals(other.schemas)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.department,
                   this.name,
                   this.permissions,
                   this.schemas
               );
    }

    @Override
    public String toString() {
        return "ScimV2UsersUpdateBody{" +
               "department=" + department +
               "name=" + name +
               "permissions=" + permissions +
               "schemas=" + schemas +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> department = Optional.empty();
        private Optional<ScimV2UsersUpdateBodyName> name = Optional.empty();
        private Optional<ScimV2UsersUpdateBodyPermissions> permissions = Optional.empty();
        private Optional<List<String>> schemas = Optional.empty();

        private Builder() {}

        public Builder from(ScimV2UsersUpdateBody other) {
            department(other.getDepartment());
            name(other.getName());
            permissions(other.getPermissions());
            schemas(other.getSchemas());
            return this;
        }

        /**
         * Sets value for `department`
         */
        @JsonSetter("department")
        public Builder department(String department) {
            this.department = Optional.ofNullable(department);

            return this;
        }

        public Builder department(Optional<String> department) {
            this.department = department;
            return this;
        }

        /**
         * Sets value for `name`
         */
        @JsonSetter("name")
        public Builder name(ScimV2UsersUpdateBodyName name) {
            this.name = Optional.ofNullable(name);

            return this;
        }

        public Builder name(Optional<ScimV2UsersUpdateBodyName> name) {
            this.name = name;
            return this;
        }

        /**
         * Sets value for `permissions`
         */
        @JsonSetter("permissions")
        public Builder permissions(ScimV2UsersUpdateBodyPermissions permissions) {
            this.permissions = Optional.ofNullable(permissions);

            return this;
        }

        public Builder permissions(Optional<ScimV2UsersUpdateBodyPermissions> permissions) {
            this.permissions = permissions;
            return this;
        }

        /**
         * Sets value for `schemas`
         */
        @JsonSetter("schemas")
        public Builder schemas(List<String> schemas) {
            this.schemas = Optional.ofNullable(schemas);

            return this;
        }

        public Builder schemas(Optional<List<String>> schemas) {
            this.schemas = schemas;
            return this;
        }


        public ScimV2UsersUpdateBody build() {
            return new ScimV2UsersUpdateBody(
                       department,
                       name,
                       permissions,
                       schemas
                   );
        }
    }

}



