
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.List;
import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * UsersDeleteCreateBody
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UsersDeleteCreateBody.Builder.class)
public final class UsersDeleteCreateBody {
    private final Optional<List<String>> brazeIds;
    private final Optional<List<String>> externalIds;
    private final Optional<List<UsersDeleteCreateBodyUserAliasesItem>> userAliases;

    private UsersDeleteCreateBody(
        Optional<List<String>> brazeIds,
        Optional<List<String>> externalIds,
        Optional<List<UsersDeleteCreateBodyUserAliasesItem>> userAliases
    ) {
        this.brazeIds = brazeIds;
        this.externalIds = externalIds;
        this.userAliases = userAliases;
    }

    /**
     * Retrieves value for `brazeIds`
     */
    @JsonProperty("braze_ids")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public List<String> getBrazeIds() {
        return brazeIds.orElse(null);
    }

    /**
     * Retrieves value for `externalIds`
     */
    @JsonProperty("external_ids")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public List<String> getExternalIds() {
        return externalIds.orElse(null);
    }

    /**
     * Retrieves value for `userAliases`
     */
    @JsonProperty("user_aliases")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public List<UsersDeleteCreateBodyUserAliasesItem> getUserAliases() {
        return userAliases.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof UsersDeleteCreateBody && equalTo((UsersDeleteCreateBody) other);
    }

    private boolean equalTo(UsersDeleteCreateBody other) {
        return
            brazeIds.equals(other.brazeIds) &&

            externalIds.equals(other.externalIds) &&

            userAliases.equals(other.userAliases)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.brazeIds,
                   this.externalIds,
                   this.userAliases
               );
    }

    @Override
    public String toString() {
        return "UsersDeleteCreateBody{" +
               "brazeIds=" + brazeIds +
               "externalIds=" + externalIds +
               "userAliases=" + userAliases +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<String>> brazeIds = Optional.empty();
        private Optional<List<String>> externalIds = Optional.empty();
        private Optional<List<UsersDeleteCreateBodyUserAliasesItem>> userAliases = Optional.empty();

        private Builder() {}

        public Builder from(UsersDeleteCreateBody other) {
            brazeIds(other.getBrazeIds());
            externalIds(other.getExternalIds());
            userAliases(other.getUserAliases());
            return this;
        }

        /**
         * Sets value for `brazeIds`
         */
        @JsonSetter("braze_ids")
        public Builder brazeIds(List<String> brazeIds) {
            this.brazeIds = Optional.ofNullable(brazeIds);

            return this;
        }

        public Builder brazeIds(Optional<List<String>> brazeIds) {
            this.brazeIds = brazeIds;
            return this;
        }

        /**
         * Sets value for `externalIds`
         */
        @JsonSetter("external_ids")
        public Builder externalIds(List<String> externalIds) {
            this.externalIds = Optional.ofNullable(externalIds);

            return this;
        }

        public Builder externalIds(Optional<List<String>> externalIds) {
            this.externalIds = externalIds;
            return this;
        }

        /**
         * Sets value for `userAliases`
         */
        @JsonSetter("user_aliases")
        public Builder userAliases(List<UsersDeleteCreateBodyUserAliasesItem> userAliases) {
            this.userAliases = Optional.ofNullable(userAliases);

            return this;
        }

        public Builder userAliases(Optional<List<UsersDeleteCreateBodyUserAliasesItem>> userAliases) {
            this.userAliases = userAliases;
            return this;
        }


        public UsersDeleteCreateBody build() {
            return new UsersDeleteCreateBody(
                       brazeIds,
                       externalIds,
                       userAliases
                   );
        }
    }

}



