
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.model;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * UsersExportIdsCreateBodyUserAliasesItem
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UsersExportIdsCreateBodyUserAliasesItem.Builder.class)
public final class UsersExportIdsCreateBodyUserAliasesItem {
    private final Optional<String> aliasLabel;
    private final Optional<String> aliasName;

    private UsersExportIdsCreateBodyUserAliasesItem(
        Optional<String> aliasLabel,
        Optional<String> aliasName
    ) {
        this.aliasLabel = aliasLabel;
        this.aliasName = aliasName;
    }

    /**
     * Retrieves value for `aliasLabel`
     */
    @JsonProperty("alias_label")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getAliasLabel() {
        return aliasLabel.orElse(null);
    }

    /**
     * Retrieves value for `aliasName`
     */
    @JsonProperty("alias_name")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getAliasName() {
        return aliasName.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof UsersExportIdsCreateBodyUserAliasesItem &&
               equalTo((UsersExportIdsCreateBodyUserAliasesItem) other);
    }

    private boolean equalTo(UsersExportIdsCreateBodyUserAliasesItem other) {
        return
            aliasLabel.equals(other.aliasLabel) &&

            aliasName.equals(other.aliasName)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.aliasLabel,
                   this.aliasName
               );
    }

    @Override
    public String toString() {
        return "UsersExportIdsCreateBodyUserAliasesItem{" +
               "aliasLabel=" + aliasLabel +
               "aliasName=" + aliasName +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> aliasLabel = Optional.empty();
        private Optional<String> aliasName = Optional.empty();

        private Builder() {}

        public Builder from(UsersExportIdsCreateBodyUserAliasesItem other) {
            aliasLabel(other.getAliasLabel());
            aliasName(other.getAliasName());
            return this;
        }

        /**
         * Sets value for `aliasLabel`
         */
        @JsonSetter("alias_label")
        public Builder aliasLabel(String aliasLabel) {
            this.aliasLabel = Optional.ofNullable(aliasLabel);

            return this;
        }

        public Builder aliasLabel(Optional<String> aliasLabel) {
            this.aliasLabel = aliasLabel;
            return this;
        }

        /**
         * Sets value for `aliasName`
         */
        @JsonSetter("alias_name")
        public Builder aliasName(String aliasName) {
            this.aliasName = Optional.ofNullable(aliasName);

            return this;
        }

        public Builder aliasName(Optional<String> aliasName) {
            this.aliasName = aliasName;
            return this;
        }


        public UsersExportIdsCreateBodyUserAliasesItem build() {
            return new UsersExportIdsCreateBodyUserAliasesItem(
                       aliasLabel,
                       aliasName
                   );
        }
    }

}



