
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.email.unsubscribes.params;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * ListRequest
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListRequest.Builder.class)
public final class ListRequest {
    /**
     * (Optional*) String
     *
     * If provided, we will return whether or not the user has unsubscribed.
     */
    private final Optional<String> email;
    /**
     * (Optional*)  String in YYYY-MM-DD format
     *
     * End date of the range to retrieve unsubscribes. This is treated as midnight in UTC time by the API.
     */
    private final Optional<String> endDate;
    /**
     * (Optional) Integer
     *
     * Optional field to limit the number of results returned. Limit must be greater than 1. Defaults to 100, maximum is 500.
     */
    private final Optional<Integer> limit;
    /**
     * (Optional) Integer
     *
     * Optional beginning point in the list to retrieve from.
     */
    private final Optional<Integer> offset;
    /**
     * (Optional) String
     *
     * Pass in the value `asc` to sort unsubscribes from oldest to newest. Pass in `desc` to sort from newest to oldest. If sort_direction is not included, the default order is newest to oldest.
     */
    private final Optional<String> sortDirection;
    /**
     * (Optional*) String in YYYY-MM-DD format
     *
     * Start date of the range to retrieve unsubscribes, must be earlier than end_date. This is treated as midnight in UTC time by the API.
     */
    private final Optional<String> startDate;

    private ListRequest(
        Optional<String> email,
        Optional<String> endDate,
        Optional<Integer> limit,
        Optional<Integer> offset,
        Optional<String> sortDirection,
        Optional<String> startDate
    ) {
        this.email = email;
        this.endDate = endDate;
        this.limit = limit;
        this.offset = offset;
        this.sortDirection = sortDirection;
        this.startDate = startDate;
    }

    /**
     * Retrieves value for `email`
     * (Optional*) String
     *
     * If provided, we will return whether or not the user has unsubscribed.
     */
    @JsonProperty("email")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getEmail() {
        return email.orElse(null);
    }

    /**
     * Retrieves value for `endDate`
     * (Optional*)  String in YYYY-MM-DD format
     *
     * End date of the range to retrieve unsubscribes. This is treated as midnight in UTC time by the API.
     */
    @JsonProperty("end_date")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getEndDate() {
        return endDate.orElse(null);
    }

    /**
     * Retrieves value for `limit`
     * (Optional) Integer
     *
     * Optional field to limit the number of results returned. Limit must be greater than 1. Defaults to 100, maximum is 500.
     */
    @JsonProperty("limit")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Integer getLimit() {
        return limit.orElse(null);
    }

    /**
     * Retrieves value for `offset`
     * (Optional) Integer
     *
     * Optional beginning point in the list to retrieve from.
     */
    @JsonProperty("offset")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Integer getOffset() {
        return offset.orElse(null);
    }

    /**
     * Retrieves value for `sortDirection`
     * (Optional) String
     *
     * Pass in the value `asc` to sort unsubscribes from oldest to newest. Pass in `desc` to sort from newest to oldest. If sort_direction is not included, the default order is newest to oldest.
     */
    @JsonProperty("sort_direction")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getSortDirection() {
        return sortDirection.orElse(null);
    }

    /**
     * Retrieves value for `startDate`
     * (Optional*) String in YYYY-MM-DD format
     *
     * Start date of the range to retrieve unsubscribes, must be earlier than end_date. This is treated as midnight in UTC time by the API.
     */
    @JsonProperty("start_date")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getStartDate() {
        return startDate.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof ListRequest && equalTo((ListRequest) other);
    }

    private boolean equalTo(ListRequest other) {
        return
            email.equals(other.email) &&

            endDate.equals(other.endDate) &&

            limit.equals(other.limit) &&

            offset.equals(other.offset) &&

            sortDirection.equals(other.sortDirection) &&

            startDate.equals(other.startDate)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.email,
                   this.endDate,
                   this.limit,
                   this.offset,
                   this.sortDirection,
                   this.startDate
               );
    }

    @Override
    public String toString() {
        return "ListRequest{" +
               "email=" + email +
               "endDate=" + endDate +
               "limit=" + limit +
               "offset=" + offset +
               "sortDirection=" + sortDirection +
               "startDate=" + startDate +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        /**
         * (Optional*) String
         *
         * If provided, we will return whether or not the user has unsubscribed.
         */
        private Optional<String> email = Optional.empty();
        /**
         * (Optional*)  String in YYYY-MM-DD format
         *
         * End date of the range to retrieve unsubscribes. This is treated as midnight in UTC time by the API.
         */
        private Optional<String> endDate = Optional.empty();
        /**
         * (Optional) Integer
         *
         * Optional field to limit the number of results returned. Limit must be greater than 1. Defaults to 100, maximum is 500.
         */
        private Optional<Integer> limit = Optional.empty();
        /**
         * (Optional) Integer
         *
         * Optional beginning point in the list to retrieve from.
         */
        private Optional<Integer> offset = Optional.empty();
        /**
         * (Optional) String
         *
         * Pass in the value `asc` to sort unsubscribes from oldest to newest. Pass in `desc` to sort from newest to oldest. If sort_direction is not included, the default order is newest to oldest.
         */
        private Optional<String> sortDirection = Optional.empty();
        /**
         * (Optional*) String in YYYY-MM-DD format
         *
         * Start date of the range to retrieve unsubscribes, must be earlier than end_date. This is treated as midnight in UTC time by the API.
         */
        private Optional<String> startDate = Optional.empty();

        private Builder() {}

        public Builder from(ListRequest other) {
            email(other.getEmail());
            endDate(other.getEndDate());
            limit(other.getLimit());
            offset(other.getOffset());
            sortDirection(other.getSortDirection());
            startDate(other.getStartDate());
            return this;
        }

        /**
         * Sets value for `email`
         * (Optional*) String
         *
         * If provided, we will return whether or not the user has unsubscribed.
         */
        @JsonSetter("email")
        public Builder email(String email) {
            this.email = Optional.ofNullable(email);

            return this;
        }

        public Builder email(Optional<String> email) {
            this.email = email;
            return this;
        }

        /**
         * Sets value for `endDate`
         * (Optional*)  String in YYYY-MM-DD format
         *
         * End date of the range to retrieve unsubscribes. This is treated as midnight in UTC time by the API.
         */
        @JsonSetter("end_date")
        public Builder endDate(String endDate) {
            this.endDate = Optional.ofNullable(endDate);

            return this;
        }

        public Builder endDate(Optional<String> endDate) {
            this.endDate = endDate;
            return this;
        }

        /**
         * Sets value for `limit`
         * (Optional) Integer
         *
         * Optional field to limit the number of results returned. Limit must be greater than 1. Defaults to 100, maximum is 500.
         */
        @JsonSetter("limit")
        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);

            return this;
        }

        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Sets value for `offset`
         * (Optional) Integer
         *
         * Optional beginning point in the list to retrieve from.
         */
        @JsonSetter("offset")
        public Builder offset(Integer offset) {
            this.offset = Optional.ofNullable(offset);

            return this;
        }

        public Builder offset(Optional<Integer> offset) {
            this.offset = offset;
            return this;
        }

        /**
         * Sets value for `sortDirection`
         * (Optional) String
         *
         * Pass in the value `asc` to sort unsubscribes from oldest to newest. Pass in `desc` to sort from newest to oldest. If sort_direction is not included, the default order is newest to oldest.
         */
        @JsonSetter("sort_direction")
        public Builder sortDirection(String sortDirection) {
            this.sortDirection = Optional.ofNullable(sortDirection);

            return this;
        }

        public Builder sortDirection(Optional<String> sortDirection) {
            this.sortDirection = sortDirection;
            return this;
        }

        /**
         * Sets value for `startDate`
         * (Optional*) String in YYYY-MM-DD format
         *
         * Start date of the range to retrieve unsubscribes, must be earlier than end_date. This is treated as midnight in UTC time by the API.
         */
        @JsonSetter("start_date")
        public Builder startDate(String startDate) {
            this.startDate = Optional.ofNullable(startDate);

            return this;
        }

        public Builder startDate(Optional<String> startDate) {
            this.startDate = startDate;
            return this;
        }


        public ListRequest build() {
            return new ListRequest(
                       email,
                       endDate,
                       limit,
                       offset,
                       sortDirection,
                       startDate
                   );
        }
    }

}



