
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.campaigns.trigger.schedule.create;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.campaigns.trigger.schedule.create.params.CreateRequest;


public class CreateClient {
    protected final BaseClient baseClient;

    public CreateClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * Schedule API Triggered Campaigns
    *
    * > Use this endpoint to send dashboard created campaign messages (up to 90 days in advance) via API-triggered delivery, allowing you to decide what action should trigger the message to be sent.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `campaigns.trigger.schedule.create` permission.
    *
    * You can pass in `trigger_properties` that will be templated into the message itself.
    *
    * Note that to send messages with this endpoint, you must have a [Campaign ID](https://www.braze.com/docs/api/identifier_types/), created when you build an [API-Triggered Campaign](https://www.braze.com/docs/api/api_campaigns/).
    *
    * ### Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * Braze endpoints support [batching API requests](https://www.braze.com/docs/api/api_limits/#batching-api-requests). A single request to the messaging endpoints can reach any of the following:
    *
    * - Up to 50 specific external_ids, each with individual message parameters
    * - A segment of any size created in the Braze dashboard, specified by its `segment_id`
    * - An ad-hoc audience segment of any size, defined in the request as a [Connected Audience](https://www.braze.com/docs/api/objects_filters/connected_audience/) object
    *
    *
    * ### Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `campaign_id` | Required | String | See [campaign identifier](https://www.braze.com/docs/api/identifier_types/) |
    * | `send_id` | Optional | String | See [send identifier](https://www.braze.com/docs/api/identifier_types/). |
    * | `recipients` | Optional | Array of recipient objects | See [recipients object](https://www.braze.com/docs/api/objects_filters/recipient_object/). |
    * | `audience` | Optional | Connected audience object | See [connected audience](https://www.braze.com/docs/api/objects_filters/connected_audience/). |
    * | `broadcast` | Optional | Boolean | See [broadcast](https://www.braze.com/docs/api/parameters/#broadcast). This parameter defaults to false (as of August 31, 2017).  <br>  <br>If `recipients` is omitted, `broadcast` must be set to true. However, use caution when setting `broadcast: true`, as unintentionally setting this flag may cause you to send your message to a larger than expected audience. |
    * | `trigger_properties` | Optional | Object | Personalization key-value pairs for all users in this send. See [trigger properties](https://www.braze.com/docs/api/objects_filters/trigger_properties_object/). |
    * | `schedule` | Required | Schedule object | See [schedule object](https://www.braze.com/docs/api/objects_filters/schedule_object/). |
    *
    * ## Response
    *
    * ### Example success response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-API-KEY-HERE
    * {
    * {
    *     "dispatch_id": "dispatch_identifier",
    *     "schedule_id": "schedule_identifier",
    *     "message": "success"
    * }
    *
    * ```
    *
    * POST /campaigns/trigger/schedule/create
    */
    public Map<?, ?> create(CreateRequest request) {
        return create(request, null);
    }


    /**
    * Schedule API Triggered Campaigns
    *
    * > Use this endpoint to send dashboard created campaign messages (up to 90 days in advance) via API-triggered delivery, allowing you to decide what action should trigger the message to be sent.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `campaigns.trigger.schedule.create` permission.
    *
    * You can pass in `trigger_properties` that will be templated into the message itself.
    *
    * Note that to send messages with this endpoint, you must have a [Campaign ID](https://www.braze.com/docs/api/identifier_types/), created when you build an [API-Triggered Campaign](https://www.braze.com/docs/api/api_campaigns/).
    *
    * ### Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * Braze endpoints support [batching API requests](https://www.braze.com/docs/api/api_limits/#batching-api-requests). A single request to the messaging endpoints can reach any of the following:
    *
    * - Up to 50 specific external_ids, each with individual message parameters
    * - A segment of any size created in the Braze dashboard, specified by its `segment_id`
    * - An ad-hoc audience segment of any size, defined in the request as a [Connected Audience](https://www.braze.com/docs/api/objects_filters/connected_audience/) object
    *
    *
    * ### Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `campaign_id` | Required | String | See [campaign identifier](https://www.braze.com/docs/api/identifier_types/) |
    * | `send_id` | Optional | String | See [send identifier](https://www.braze.com/docs/api/identifier_types/). |
    * | `recipients` | Optional | Array of recipient objects | See [recipients object](https://www.braze.com/docs/api/objects_filters/recipient_object/). |
    * | `audience` | Optional | Connected audience object | See [connected audience](https://www.braze.com/docs/api/objects_filters/connected_audience/). |
    * | `broadcast` | Optional | Boolean | See [broadcast](https://www.braze.com/docs/api/parameters/#broadcast). This parameter defaults to false (as of August 31, 2017).  <br>  <br>If `recipients` is omitted, `broadcast` must be set to true. However, use caution when setting `broadcast: true`, as unintentionally setting this flag may cause you to send your message to a larger than expected audience. |
    * | `trigger_properties` | Optional | Object | Personalization key-value pairs for all users in this send. See [trigger properties](https://www.braze.com/docs/api/objects_filters/trigger_properties_object/). |
    * | `schedule` | Required | Schedule object | See [schedule object](https://www.braze.com/docs/api/objects_filters/schedule_object/). |
    *
    * ## Response
    *
    * ### Example success response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-API-KEY-HERE
    * {
    * {
    *     "dispatch_id": "dispatch_identifier",
    *     "schedule_id": "schedule_identifier",
    *     "message": "success"
    * }
    *
    * ```
    *
    * POST /campaigns/trigger/schedule/create
    */
    public Map<?, ?> create(CreateRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/campaigns/trigger/schedule/create")
            .method("POST")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .setJsonBody(request.getData())
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
