
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.segments;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.segments.dataseries.DataSeriesClient;
import com.yourorg.brazejava.resources.segments.details.DetailsClient;
import com.yourorg.brazejava.resources.segments.list.ListClient;


public class SegmentsClient {
    protected final BaseClient baseClient;
    protected final Supplier<DataSeriesClient> dataSeries;
    protected final Supplier<DetailsClient> details;
    protected final Supplier<ListClient> list;
    public SegmentsClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.dataSeries = Suppliers.memoize(() -> new DataSeriesClient(baseClient));
        this.details = Suppliers.memoize(() -> new DetailsClient(baseClient));
        this.list = Suppliers.memoize(() -> new ListClient(baseClient));
    }

    public DataSeriesClient dataSeries() {
        return this.dataSeries.get();
    }

    public DetailsClient details() {
        return this.details.get();
    }

    public ListClient list() {
        return this.list.get();
    }
}
