
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.subscription.user.status.params;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * ListRequest
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListRequest.Builder.class)
public final class ListRequest {
    /**
     * (Required*) String
     *
     * The `external_id` of the user (must include at least one and at most 50 `external_ids`).
     */
    private final Optional<String> externalId;
    /**
     * (Optional) Integer
     *
     * The limit on the maximum number of results returned. Default (and max) limit is 100.
     */
    private final Optional<Integer> limit;
    /**
     * (Optional) Integer
     *
     *  Number of templates to skip before returning the rest of the templates that fit the search criteria.
     */
    private final Optional<Integer> offset;
    /**
     * (Required*) String in [E.164](https://en.wikipedia.org/wiki/E.164) format
     *
     * The phone number of the user. Must include at least one phone number (with a max of 50).
     */
    private final Optional<String> phone;

    private ListRequest(
        Optional<String> externalId,
        Optional<Integer> limit,
        Optional<Integer> offset,
        Optional<String> phone
    ) {
        this.externalId = externalId;
        this.limit = limit;
        this.offset = offset;
        this.phone = phone;
    }

    /**
     * Retrieves value for `externalId`
     * (Required*) String
     *
     * The `external_id` of the user (must include at least one and at most 50 `external_ids`).
     */
    @JsonProperty("external_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getExternalId() {
        return externalId.orElse(null);
    }

    /**
     * Retrieves value for `limit`
     * (Optional) Integer
     *
     * The limit on the maximum number of results returned. Default (and max) limit is 100.
     */
    @JsonProperty("limit")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Integer getLimit() {
        return limit.orElse(null);
    }

    /**
     * Retrieves value for `offset`
     * (Optional) Integer
     *
     *  Number of templates to skip before returning the rest of the templates that fit the search criteria.
     */
    @JsonProperty("offset")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Integer getOffset() {
        return offset.orElse(null);
    }

    /**
     * Retrieves value for `phone`
     * (Required*) String in [E.164](https://en.wikipedia.org/wiki/E.164) format
     *
     * The phone number of the user. Must include at least one phone number (with a max of 50).
     */
    @JsonProperty("phone")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getPhone() {
        return phone.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof ListRequest && equalTo((ListRequest) other);
    }

    private boolean equalTo(ListRequest other) {
        return
            externalId.equals(other.externalId) &&

            limit.equals(other.limit) &&

            offset.equals(other.offset) &&

            phone.equals(other.phone)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.externalId,
                   this.limit,
                   this.offset,
                   this.phone
               );
    }

    @Override
    public String toString() {
        return "ListRequest{" +
               "externalId=" + externalId +
               "limit=" + limit +
               "offset=" + offset +
               "phone=" + phone +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        /**
         * (Required*) String
         *
         * The `external_id` of the user (must include at least one and at most 50 `external_ids`).
         */
        private Optional<String> externalId = Optional.empty();
        /**
         * (Optional) Integer
         *
         * The limit on the maximum number of results returned. Default (and max) limit is 100.
         */
        private Optional<Integer> limit = Optional.empty();
        /**
         * (Optional) Integer
         *
         *  Number of templates to skip before returning the rest of the templates that fit the search criteria.
         */
        private Optional<Integer> offset = Optional.empty();
        /**
         * (Required*) String in [E.164](https://en.wikipedia.org/wiki/E.164) format
         *
         * The phone number of the user. Must include at least one phone number (with a max of 50).
         */
        private Optional<String> phone = Optional.empty();

        private Builder() {}

        public Builder from(ListRequest other) {
            externalId(other.getExternalId());
            limit(other.getLimit());
            offset(other.getOffset());
            phone(other.getPhone());
            return this;
        }

        /**
         * Sets value for `externalId`
         * (Required*) String
         *
         * The `external_id` of the user (must include at least one and at most 50 `external_ids`).
         */
        @JsonSetter("external_id")
        public Builder externalId(String externalId) {
            this.externalId = Optional.ofNullable(externalId);

            return this;
        }

        public Builder externalId(Optional<String> externalId) {
            this.externalId = externalId;
            return this;
        }

        /**
         * Sets value for `limit`
         * (Optional) Integer
         *
         * The limit on the maximum number of results returned. Default (and max) limit is 100.
         */
        @JsonSetter("limit")
        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);

            return this;
        }

        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Sets value for `offset`
         * (Optional) Integer
         *
         *  Number of templates to skip before returning the rest of the templates that fit the search criteria.
         */
        @JsonSetter("offset")
        public Builder offset(Integer offset) {
            this.offset = Optional.ofNullable(offset);

            return this;
        }

        public Builder offset(Optional<Integer> offset) {
            this.offset = offset;
            return this;
        }

        /**
         * Sets value for `phone`
         * (Required*) String in [E.164](https://en.wikipedia.org/wiki/E.164) format
         *
         * The phone number of the user. Must include at least one phone number (with a max of 50).
         */
        @JsonSetter("phone")
        public Builder phone(String phone) {
            this.phone = Optional.ofNullable(phone);

            return this;
        }

        public Builder phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }


        public ListRequest build() {
            return new ListRequest(
                       externalId,
                       limit,
                       offset,
                       phone
                   );
        }
    }

}



