
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.sms.invalidphonenumbers.remove;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.sms.invalidphonenumbers.remove.params.CreateRequest;


public class RemoveClient {
    protected final BaseClient baseClient;

    public RemoveClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * Remove Invalid Phone Numbers
    *
    * > Use this endpoint to remove “invalid” phone numbers from Braze’s invalid list.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `sms.invalid_phone_numbers.remove` permission.
    *
    * This can be used to re-validate phone numbers after they have been marked as invalid.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `phone_number` | Required | Array of strings in e.164 format | An array of up to 50 phone numbers to modify. |
    *
    * POST /sms/invalid_phone_numbers/remove
    */
    public Map<?, ?> create(CreateRequest request) {
        return create(request, null);
    }


    /**
    * Remove Invalid Phone Numbers
    *
    * > Use this endpoint to remove “invalid” phone numbers from Braze’s invalid list.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `sms.invalid_phone_numbers.remove` permission.
    *
    * This can be used to re-validate phone numbers after they have been marked as invalid.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `phone_number` | Required | Array of strings in e.164 format | An array of up to 50 phone numbers to modify. |
    *
    * POST /sms/invalid_phone_numbers/remove
    */
    public Map<?, ?> create(CreateRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/sms/invalid_phone_numbers/remove")
            .method("POST")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .setJsonBody(request.getData())
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
