
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.contentblocks.list;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.contentblocks.list.params.ListRequest;


public class ListClient {
    protected final BaseClient baseClient;

    public ListClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * List Available Content Blocks
    *
    * > Use this endpoint to list your existing [Content Blocks](https://www.braze.com/docs/user_guide/engagement_tools/templates_and_media/content_blocks/) information.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `content_blocks.list` permission.
    *
    * ### Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ### Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR_REST_API_KEY
    * {
    *   "count": "integer",
    *   "content_blocks": [
    *     {
    *       "content_block_id": "string",
    *       "name": "string",
    *       "content_type": "html or text",
    *       "liquid_tag": "string",
    *       "inclusion_count" : "integer",
    *       "created_at": "time-in-iso",
    *       "last_edited": "time-in-iso",
    *       "tags" : "array of strings"
    *     }
    *   ]
    * }
    *
    * ```
    *
    * ## Troubleshooting
    *
    * The following table lists possible returned errors and their associated troubleshooting steps.
    *
    * | Error | Troubleshooting |
    * | --- | --- |
    * | `Modified after time is invalid` | The provided date is not a valid or parsable date. Reformat this value as a string in ISO 8601 format (`yyyy-mm-ddThh:mm:ss.ffffff`). |
    * | `Modified before time is invalid` | The provided date is not a valid or parsable date. Reformat this value as a string in ISO 8601 format (`yyyy-mm-ddThh:mm:ss.ffffff`). |
    * | `Modified after time must be earlier than or the same as modified before time.` | Change the `modified_after` value to a time that is earlier than the `modified_before` time. |
    * | `Content Block number limit is invalid` | The `limit` parameter must be an integer (positive number) greater than 0. |
    * | `Content Block number limit must be greater than 0` | Change the `limit` parameter to an integer greater than 0. |
    * | `Content Block number limit exceeds maximum of 1000` | Change the `limit` parameter to an integer less than 1000. |
    * | `Offset is invalid` | The `offset` parameter must be an integer greater than 0. |
    * | Offset must be greater than 0 | Change the `offset` parameter to an integer greater than 0. |
    *
    * GET /content_blocks/list
    */
    public Map<?, ?> list() {
        return list(ListRequest.builder().build(), null);
    }


    /**
    * List Available Content Blocks
    *
    * > Use this endpoint to list your existing [Content Blocks](https://www.braze.com/docs/user_guide/engagement_tools/templates_and_media/content_blocks/) information.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `content_blocks.list` permission.
    *
    * ### Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ### Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR_REST_API_KEY
    * {
    *   "count": "integer",
    *   "content_blocks": [
    *     {
    *       "content_block_id": "string",
    *       "name": "string",
    *       "content_type": "html or text",
    *       "liquid_tag": "string",
    *       "inclusion_count" : "integer",
    *       "created_at": "time-in-iso",
    *       "last_edited": "time-in-iso",
    *       "tags" : "array of strings"
    *     }
    *   ]
    * }
    *
    * ```
    *
    * ## Troubleshooting
    *
    * The following table lists possible returned errors and their associated troubleshooting steps.
    *
    * | Error | Troubleshooting |
    * | --- | --- |
    * | `Modified after time is invalid` | The provided date is not a valid or parsable date. Reformat this value as a string in ISO 8601 format (`yyyy-mm-ddThh:mm:ss.ffffff`). |
    * | `Modified before time is invalid` | The provided date is not a valid or parsable date. Reformat this value as a string in ISO 8601 format (`yyyy-mm-ddThh:mm:ss.ffffff`). |
    * | `Modified after time must be earlier than or the same as modified before time.` | Change the `modified_after` value to a time that is earlier than the `modified_before` time. |
    * | `Content Block number limit is invalid` | The `limit` parameter must be an integer (positive number) greater than 0. |
    * | `Content Block number limit must be greater than 0` | Change the `limit` parameter to an integer greater than 0. |
    * | `Content Block number limit exceeds maximum of 1000` | Change the `limit` parameter to an integer less than 1000. |
    * | `Offset is invalid` | The `offset` parameter must be an integer greater than 0. |
    * | Offset must be greater than 0 | Change the `offset` parameter to an integer greater than 0. |
    *
    * GET /content_blocks/list
    */
    public Map<?, ?> list(ListRequest request) {
        return list(request, null);
    }


    /**
    * List Available Content Blocks
    *
    * > Use this endpoint to list your existing [Content Blocks](https://www.braze.com/docs/user_guide/engagement_tools/templates_and_media/content_blocks/) information.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `content_blocks.list` permission.
    *
    * ### Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ### Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR_REST_API_KEY
    * {
    *   "count": "integer",
    *   "content_blocks": [
    *     {
    *       "content_block_id": "string",
    *       "name": "string",
    *       "content_type": "html or text",
    *       "liquid_tag": "string",
    *       "inclusion_count" : "integer",
    *       "created_at": "time-in-iso",
    *       "last_edited": "time-in-iso",
    *       "tags" : "array of strings"
    *     }
    *   ]
    * }
    *
    * ```
    *
    * ## Troubleshooting
    *
    * The following table lists possible returned errors and their associated troubleshooting steps.
    *
    * | Error | Troubleshooting |
    * | --- | --- |
    * | `Modified after time is invalid` | The provided date is not a valid or parsable date. Reformat this value as a string in ISO 8601 format (`yyyy-mm-ddThh:mm:ss.ffffff`). |
    * | `Modified before time is invalid` | The provided date is not a valid or parsable date. Reformat this value as a string in ISO 8601 format (`yyyy-mm-ddThh:mm:ss.ffffff`). |
    * | `Modified after time must be earlier than or the same as modified before time.` | Change the `modified_after` value to a time that is earlier than the `modified_before` time. |
    * | `Content Block number limit is invalid` | The `limit` parameter must be an integer (positive number) greater than 0. |
    * | `Content Block number limit must be greater than 0` | Change the `limit` parameter to an integer greater than 0. |
    * | `Content Block number limit exceeds maximum of 1000` | Change the `limit` parameter to an integer less than 1000. |
    * | `Offset is invalid` | The `offset` parameter must be an integer greater than 0. |
    * | Offset must be greater than 0 | Change the `offset` parameter to an integer greater than 0. |
    *
    * GET /content_blocks/list
    */
    public Map<?, ?> list(ListRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/content_blocks/list")
            .addQueryParam("limit", request.getLimit(), "form", true)
            .addQueryParam("modified_after", request.getModifiedAfter(), "form", true)
            .addQueryParam("modified_before", request.getModifiedBefore(), "form", true)
            .addQueryParam("offset", request.getOffset(), "form", true)
            .method("GET")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
