
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.subscription.status;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.subscription.status.get.GetClient;
import com.yourorg.brazejava.resources.subscription.status.set.SetClient;


public class StatusClient {
    protected final BaseClient baseClient;
    protected final Supplier<GetClient> get;
    protected final Supplier<SetClient> set;
    public StatusClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.get = Suppliers.memoize(() -> new GetClient(baseClient));
        this.set = Suppliers.memoize(() -> new SetClient(baseClient));
    }

    public GetClient get() {
        return this.get.get();
    }

    public SetClient set() {
        return this.set.get();
    }
}
