
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.sends.id;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.sends.id.create.CreateClient;


public class IdClient {
    protected final BaseClient baseClient;
    protected final Supplier<CreateClient> create;
    public IdClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.create = Suppliers.memoize(() -> new CreateClient(baseClient));
    }

    public CreateClient create() {
        return this.create.get();
    }
}
