
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.purchases.productlist;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.purchases.productlist.params.ListRequest;


public class ProductListClient {
    protected final BaseClient baseClient;

    public ProductListClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * Export Product IDs
    *
    * > Use this endpoint to return a paginated lists of product IDs.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `purchases.product_list` permission.
    *
    * ## Rate limit
    *
    * For customers who onboarded with Braze on or after September 16, 2021, we apply a shared rate limit of 1,000 requests per hour to this endpoint. This rate limit is shared with the `/events/list` endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *   "products": [
    *     "product_name" (string), the name of the product
    *   ],
    *   "message": "success"
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /purchases/product_list
    */
    public Map<?, ?> list() {
        return list(ListRequest.builder().build(), null);
    }


    /**
    * Export Product IDs
    *
    * > Use this endpoint to return a paginated lists of product IDs.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `purchases.product_list` permission.
    *
    * ## Rate limit
    *
    * For customers who onboarded with Braze on or after September 16, 2021, we apply a shared rate limit of 1,000 requests per hour to this endpoint. This rate limit is shared with the `/events/list` endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *   "products": [
    *     "product_name" (string), the name of the product
    *   ],
    *   "message": "success"
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /purchases/product_list
    */
    public Map<?, ?> list(ListRequest request) {
        return list(request, null);
    }


    /**
    * Export Product IDs
    *
    * > Use this endpoint to return a paginated lists of product IDs.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `purchases.product_list` permission.
    *
    * ## Rate limit
    *
    * For customers who onboarded with Braze on or after September 16, 2021, we apply a shared rate limit of 1,000 requests per hour to this endpoint. This rate limit is shared with the `/events/list` endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *   "products": [
    *     "product_name" (string), the name of the product
    *   ],
    *   "message": "success"
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /purchases/product_list
    */
    public Map<?, ?> list(ListRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/purchases/product_list")
            .addQueryParam("page", request.getPage(), "form", true)
            .method("GET")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
