
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.catalogs.items.params;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yourorg.brazejava.model.CatalogsItemsCreateBody;


/**
 * CreateRequest
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateRequest.Builder.class)
public final class CreateRequest {
    private final Optional<CatalogsItemsCreateBody> data;
    private final String catalogName;

    private CreateRequest(
        Optional<CatalogsItemsCreateBody> data,
        String catalogName
    ) {
        this.data = data;
        this.catalogName = catalogName;
    }

    /**
     * Retrieves value for `data`
     */
    @JsonProperty("data")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public CatalogsItemsCreateBody getData() {
        return data.orElse(null);
    }

    /**
     * Retrieves value for `catalogName`
     */
    @JsonProperty("catalog_name")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getCatalogName() {
        return catalogName;
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof CreateRequest && equalTo((CreateRequest) other);
    }

    private boolean equalTo(CreateRequest other) {
        return
            data.equals(other.data) &&

            catalogName.equals(other.catalogName)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.data,
                   this.catalogName
               );
    }

    @Override
    public String toString() {
        return "CreateRequest{" +
               "data=" + data +
               "catalogName=" + catalogName +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<CatalogsItemsCreateBody> data = Optional.empty();
        private String catalogName = null;

        private Builder() {}

        public Builder from(CreateRequest other) {
            data(other.getData());
            catalogName(other.getCatalogName());
            return this;
        }

        /**
         * Sets value for `data`
         */
        @JsonSetter("data")
        public Builder data(CatalogsItemsCreateBody data) {
            this.data = Optional.ofNullable(data);

            return this;
        }

        public Builder data(Optional<CatalogsItemsCreateBody> data) {
            this.data = data;
            return this;
        }

        /**
         * Sets value for `catalogName`
         */
        @JsonSetter("catalog_name")
        public Builder catalogName(String catalogName) {
            if (catalogName == null) {
                throw new IllegalArgumentException("catalogName cannot be null");
            }

            this.catalogName = catalogName;

            return this;
        }



        public CreateRequest build() {
            if (catalogName == null) {
                throw new IllegalStateException("catalogName is required");
            }

            return new CreateRequest(
                       data,
                       catalogName
                   );
        }
    }

}



