
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.email.blocklist;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.email.blocklist.params.CreateRequest;


public class BlocklistClient {
    protected final BaseClient baseClient;

    public BlocklistClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * Blocklist Email Addresses
    *
    * > Use this endpoint to unsubscribe a user from email and mark them as hard bounced.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `email.blacklist` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `email` | Required | String or array | String email address to blacklist, or an array of up to 50 email addresses to blocklist. |
    *
    * POST /email/blocklist
    */
    public Map<?, ?> create(CreateRequest request) {
        return create(request, null);
    }


    /**
    * Blocklist Email Addresses
    *
    * > Use this endpoint to unsubscribe a user from email and mark them as hard bounced.
    *
    *
    * To use this endpoint, you’ll need to generate an API key with the `email.blacklist` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `email` | Required | String or array | String email address to blacklist, or an array of up to 50 email addresses to blocklist. |
    *
    * POST /email/blocklist
    */
    public Map<?, ?> create(CreateRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/email/blocklist")
            .method("POST")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .setJsonBody(request.getData())
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
