
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.email.spam;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.email.spam.remove.RemoveClient;


public class SpamClient {
    protected final BaseClient baseClient;
    protected final Supplier<RemoveClient> remove;
    public SpamClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.remove = Suppliers.memoize(() -> new RemoveClient(baseClient));
    }

    public RemoveClient remove() {
        return this.remove.get();
    }
}
