
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.users.export;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.users.export.globalcontrolgroup.GlobalControlGroupClient;
import com.yourorg.brazejava.resources.users.export.ids.IdsClient;
import com.yourorg.brazejava.resources.users.export.segment.SegmentClient;


public class ExportClient {
    protected final BaseClient baseClient;
    protected final Supplier<GlobalControlGroupClient> globalControlGroup;
    protected final Supplier<IdsClient> ids;
    protected final Supplier<SegmentClient> segment;
    public ExportClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.globalControlGroup = Suppliers.memoize(() -> new GlobalControlGroupClient(baseClient));
        this.ids = Suppliers.memoize(() -> new IdsClient(baseClient));
        this.segment = Suppliers.memoize(() -> new SegmentClient(baseClient));
    }

    public GlobalControlGroupClient globalControlGroup() {
        return this.globalControlGroup.get();
    }

    public IdsClient ids() {
        return this.ids.get();
    }

    public SegmentClient segment() {
        return this.segment.get();
    }
}
