
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.kpi.newusers.dataseries;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.kpi.newusers.dataseries.params.ListRequest;


public class DataSeriesClient {
    protected final BaseClient baseClient;

    public DataSeriesClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * Export Daily New Users by Date
    *
    * > Use this endpoint to retrieve a daily series of the total number of new users on each date.
    *
    *
    * Note: If you are using our [older navigation](https://www.braze.com/docs/navigation), `app_id` can be found at **Developer Console** > **API Settings**.
    *
    * To use this endpoint, you’ll need to generate an API key with the `kpi.new_users.data_series` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *     "message": (required, string) the status of the export, returns 'success' when completed without errors,
    *     "data" : [
    *         {
    *             "time" : (string) the date as ISO 8601 date,
    *             "new_users" : (int) the number of daily new users
    *         },
    *         ...
    *     ]
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /kpi/new_users/data_series
    */
    public Map<?, ?> list() {
        return list(ListRequest.builder().build(), null);
    }


    /**
    * Export Daily New Users by Date
    *
    * > Use this endpoint to retrieve a daily series of the total number of new users on each date.
    *
    *
    * Note: If you are using our [older navigation](https://www.braze.com/docs/navigation), `app_id` can be found at **Developer Console** > **API Settings**.
    *
    * To use this endpoint, you’ll need to generate an API key with the `kpi.new_users.data_series` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *     "message": (required, string) the status of the export, returns 'success' when completed without errors,
    *     "data" : [
    *         {
    *             "time" : (string) the date as ISO 8601 date,
    *             "new_users" : (int) the number of daily new users
    *         },
    *         ...
    *     ]
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /kpi/new_users/data_series
    */
    public Map<?, ?> list(ListRequest request) {
        return list(request, null);
    }


    /**
    * Export Daily New Users by Date
    *
    * > Use this endpoint to retrieve a daily series of the total number of new users on each date.
    *
    *
    * Note: If you are using our [older navigation](https://www.braze.com/docs/navigation), `app_id` can be found at **Developer Console** > **API Settings**.
    *
    * To use this endpoint, you’ll need to generate an API key with the `kpi.new_users.data_series` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *     "message": (required, string) the status of the export, returns 'success' when completed without errors,
    *     "data" : [
    *         {
    *             "time" : (string) the date as ISO 8601 date,
    *             "new_users" : (int) the number of daily new users
    *         },
    *         ...
    *     ]
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /kpi/new_users/data_series
    */
    public Map<?, ?> list(ListRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/kpi/new_users/data_series")
            .addQueryParam("app_id", request.getAppId(), "form", true)
            .addQueryParam("ending_at", request.getEndingAt(), "form", true)
            .addQueryParam("length", request.getLength(), "form", true)
            .method("GET")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
