
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.purchases;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.purchases.productlist.ProductListClient;
import com.yourorg.brazejava.resources.purchases.quantityseries.QuantitySeriesClient;
import com.yourorg.brazejava.resources.purchases.revenueseries.RevenueSeriesClient;


public class PurchasesClient {
    protected final BaseClient baseClient;
    protected final Supplier<ProductListClient> productList;
    protected final Supplier<QuantitySeriesClient> quantitySeries;
    protected final Supplier<RevenueSeriesClient> revenueSeries;
    public PurchasesClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.productList = Suppliers.memoize(() -> new ProductListClient(baseClient));
        this.quantitySeries = Suppliers.memoize(() -> new QuantitySeriesClient(baseClient));
        this.revenueSeries = Suppliers.memoize(() -> new RevenueSeriesClient(baseClient));
    }

    public ProductListClient productList() {
        return this.productList.get();
    }

    public QuantitySeriesClient quantitySeries() {
        return this.quantitySeries.get();
    }

    public RevenueSeriesClient revenueSeries() {
        return this.revenueSeries.get();
    }
}
