
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.feed.dataseries;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.feed.dataseries.params.ListRequest;


public class DataSeriesClient {
    protected final BaseClient baseClient;

    public DataSeriesClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * Export News Feed Card Analytics
    *
    * > Use this endpoint to retrieve a daily series of engagement stats for a card over time.
    *
    *
    * Note: If you are using our [older navigation](https://www.braze.com/docs/navigation), \`card_id\` can be found at **Developer Console > API Settings**.
    *
    * To use this endpoint, you’ll need to generate an API key with the `feed.data_series` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *     "message": (required, string) the status of the export, returns 'success' when completed without errors,
    *     "data" : [
    *         {
    *             "time" : (string) the point in time - as ISO 8601 extended when unit is "hour" and as ISO 8601 date when unit is "day",
    *             "clicks" : (int) the number of clicks,
    *             "impressions" : (int) the number of impressions,
    *             "unique_clicks" : (int) the number of unique clicks,
    *             "unique_impressions" : (int) the number of unique impressions
    *         },
    *         ...
    *     ]
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /feed/data_series
    */
    public Map<?, ?> list() {
        return list(ListRequest.builder().build(), null);
    }


    /**
    * Export News Feed Card Analytics
    *
    * > Use this endpoint to retrieve a daily series of engagement stats for a card over time.
    *
    *
    * Note: If you are using our [older navigation](https://www.braze.com/docs/navigation), \`card_id\` can be found at **Developer Console > API Settings**.
    *
    * To use this endpoint, you’ll need to generate an API key with the `feed.data_series` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *     "message": (required, string) the status of the export, returns 'success' when completed without errors,
    *     "data" : [
    *         {
    *             "time" : (string) the point in time - as ISO 8601 extended when unit is "hour" and as ISO 8601 date when unit is "day",
    *             "clicks" : (int) the number of clicks,
    *             "impressions" : (int) the number of impressions,
    *             "unique_clicks" : (int) the number of unique clicks,
    *             "unique_impressions" : (int) the number of unique impressions
    *         },
    *         ...
    *     ]
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /feed/data_series
    */
    public Map<?, ?> list(ListRequest request) {
        return list(request, null);
    }


    /**
    * Export News Feed Card Analytics
    *
    * > Use this endpoint to retrieve a daily series of engagement stats for a card over time.
    *
    *
    * Note: If you are using our [older navigation](https://www.braze.com/docs/navigation), \`card_id\` can be found at **Developer Console > API Settings**.
    *
    * To use this endpoint, you’ll need to generate an API key with the `feed.data_series` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *     "message": (required, string) the status of the export, returns 'success' when completed without errors,
    *     "data" : [
    *         {
    *             "time" : (string) the point in time - as ISO 8601 extended when unit is "hour" and as ISO 8601 date when unit is "day",
    *             "clicks" : (int) the number of clicks,
    *             "impressions" : (int) the number of impressions,
    *             "unique_clicks" : (int) the number of unique clicks,
    *             "unique_impressions" : (int) the number of unique impressions
    *         },
    *         ...
    *     ]
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /feed/data_series
    */
    public Map<?, ?> list(ListRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/feed/data_series")
            .addQueryParam("card_id", request.getCardId(), "form", true)
            .addQueryParam("ending_at", request.getEndingAt(), "form", true)
            .addQueryParam("length", request.getLength(), "form", true)
            .addQueryParam("unit", request.getUnit(), "form", true)
            .method("GET")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
