
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.v2.subscription;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.v2.subscription.status.StatusClient;


public class SubscriptionClient {
    protected final BaseClient baseClient;
    protected final Supplier<StatusClient> status;
    public SubscriptionClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.status = Suppliers.memoize(() -> new StatusClient(baseClient));
    }

    public StatusClient status() {
        return this.status.get();
    }
}
