
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.feed.dataseries.params;

import java.util.Objects;
import java.util.Optional;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;


/**
 * ListRequest
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListRequest.Builder.class)
public final class ListRequest {
    /**
     * (Required) String
     *
     * See [Card API identifier](https://www.braze.com/docs/api/identifier_types/).
     *
     * The `card_id` for a given card can be found in the **Settings > Setup and Testing > API Keys** page and on the card details page within your dashboard, or you can use the [News Feed List Endpoint](https://www.braze.com/docs/api/endpoints/export/news_feed/get_news_feed_cards/).
     */
    private final Optional<String> cardId;
    /**
     * (Optional) Datetime ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string)
     *
     * Date on which the data series should end. Defaults to time of the request.
     *
     */
    private final Optional<String> endingAt;
    /**
     * (Required) Integer
     *
     * Max number of units (days or hours) before `ending_at` to include in the returned series. Must be between 1 and 100 (inclusive).
     */
    private final Optional<Integer> length;
    /**
     * (Optional) String
     *
     * Unit of time between data points. Can be `day` or `hour`, defaults to `day`.
     */
    private final Optional<String> unit;

    private ListRequest(
        Optional<String> cardId,
        Optional<String> endingAt,
        Optional<Integer> length,
        Optional<String> unit
    ) {
        this.cardId = cardId;
        this.endingAt = endingAt;
        this.length = length;
        this.unit = unit;
    }

    /**
     * Retrieves value for `cardId`
     * (Required) String
     *
     * See [Card API identifier](https://www.braze.com/docs/api/identifier_types/).
     *
     * The `card_id` for a given card can be found in the **Settings > Setup and Testing > API Keys** page and on the card details page within your dashboard, or you can use the [News Feed List Endpoint](https://www.braze.com/docs/api/endpoints/export/news_feed/get_news_feed_cards/).
     */
    @JsonProperty("card_id")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getCardId() {
        return cardId.orElse(null);
    }

    /**
     * Retrieves value for `endingAt`
     * (Optional) Datetime ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string)
     *
     * Date on which the data series should end. Defaults to time of the request.
     *
     */
    @JsonProperty("ending_at")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getEndingAt() {
        return endingAt.orElse(null);
    }

    /**
     * Retrieves value for `length`
     * (Required) Integer
     *
     * Max number of units (days or hours) before `ending_at` to include in the returned series. Must be between 1 and 100 (inclusive).
     */
    @JsonProperty("length")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public Integer getLength() {
        return length.orElse(null);
    }

    /**
     * Retrieves value for `unit`
     * (Optional) String
     *
     * Unit of time between data points. Can be `day` or `hour`, defaults to `day`.
     */
    @JsonProperty("unit")
    @JsonInclude(JsonInclude.Include.NON_ABSENT)
    public String getUnit() {
        return unit.orElse(null);
    }


    @Override
    public boolean equals(Object other) {
        if (this == other) { return true; }

        return other instanceof ListRequest && equalTo((ListRequest) other);
    }

    private boolean equalTo(ListRequest other) {
        return
            cardId.equals(other.cardId) &&

            endingAt.equals(other.endingAt) &&

            length.equals(other.length) &&

            unit.equals(other.unit)
            ;
    }

    @Override
    public int hashCode() {
        return Objects.hash(
                   this.cardId,
                   this.endingAt,
                   this.length,
                   this.unit
               );
    }

    @Override
    public String toString() {
        return "ListRequest{" +
               "cardId=" + cardId +
               "endingAt=" + endingAt +
               "length=" + length +
               "unit=" + unit +
               '}';
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        /**
         * (Required) String
         *
         * See [Card API identifier](https://www.braze.com/docs/api/identifier_types/).
         *
         * The `card_id` for a given card can be found in the **Settings > Setup and Testing > API Keys** page and on the card details page within your dashboard, or you can use the [News Feed List Endpoint](https://www.braze.com/docs/api/endpoints/export/news_feed/get_news_feed_cards/).
         */
        private Optional<String> cardId = Optional.empty();
        /**
         * (Optional) Datetime ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string)
         *
         * Date on which the data series should end. Defaults to time of the request.
         *
         */
        private Optional<String> endingAt = Optional.empty();
        /**
         * (Required) Integer
         *
         * Max number of units (days or hours) before `ending_at` to include in the returned series. Must be between 1 and 100 (inclusive).
         */
        private Optional<Integer> length = Optional.empty();
        /**
         * (Optional) String
         *
         * Unit of time between data points. Can be `day` or `hour`, defaults to `day`.
         */
        private Optional<String> unit = Optional.empty();

        private Builder() {}

        public Builder from(ListRequest other) {
            cardId(other.getCardId());
            endingAt(other.getEndingAt());
            length(other.getLength());
            unit(other.getUnit());
            return this;
        }

        /**
         * Sets value for `cardId`
         * (Required) String
         *
         * See [Card API identifier](https://www.braze.com/docs/api/identifier_types/).
         *
         * The `card_id` for a given card can be found in the **Settings > Setup and Testing > API Keys** page and on the card details page within your dashboard, or you can use the [News Feed List Endpoint](https://www.braze.com/docs/api/endpoints/export/news_feed/get_news_feed_cards/).
         */
        @JsonSetter("card_id")
        public Builder cardId(String cardId) {
            this.cardId = Optional.ofNullable(cardId);

            return this;
        }

        public Builder cardId(Optional<String> cardId) {
            this.cardId = cardId;
            return this;
        }

        /**
         * Sets value for `endingAt`
         * (Optional) Datetime ([ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) string)
         *
         * Date on which the data series should end. Defaults to time of the request.
         *
         */
        @JsonSetter("ending_at")
        public Builder endingAt(String endingAt) {
            this.endingAt = Optional.ofNullable(endingAt);

            return this;
        }

        public Builder endingAt(Optional<String> endingAt) {
            this.endingAt = endingAt;
            return this;
        }

        /**
         * Sets value for `length`
         * (Required) Integer
         *
         * Max number of units (days or hours) before `ending_at` to include in the returned series. Must be between 1 and 100 (inclusive).
         */
        @JsonSetter("length")
        public Builder length(Integer length) {
            this.length = Optional.ofNullable(length);

            return this;
        }

        public Builder length(Optional<Integer> length) {
            this.length = length;
            return this;
        }

        /**
         * Sets value for `unit`
         * (Optional) String
         *
         * Unit of time between data points. Can be `day` or `hour`, defaults to `day`.
         */
        @JsonSetter("unit")
        public Builder unit(String unit) {
            this.unit = Optional.ofNullable(unit);

            return this;
        }

        public Builder unit(Optional<String> unit) {
            this.unit = unit;
            return this;
        }


        public ListRequest build() {
            return new ListRequest(
                       cardId,
                       endingAt,
                       length,
                       unit
                   );
        }
    }

}



