
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.scim;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.scim.v2.V2Client;


public class ScimClient {
    protected final BaseClient baseClient;
    protected final Supplier<V2Client> v2;
    public ScimClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.v2 = Suppliers.memoize(() -> new V2Client(baseClient));
    }

    public V2Client v2() {
        return this.v2.get();
    }
}
