
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.users.externalids;

import java.util.function.Supplier;

import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.Suppliers;
import com.yourorg.brazejava.resources.users.externalids.remove.RemoveClient;
import com.yourorg.brazejava.resources.users.externalids.rename.RenameClient;


public class ExternalIdsClient {
    protected final BaseClient baseClient;
    protected final Supplier<RemoveClient> remove;
    protected final Supplier<RenameClient> rename;
    public ExternalIdsClient(BaseClient baseClient) {
        this.baseClient = baseClient;
        this.remove = Suppliers.memoize(() -> new RemoveClient(baseClient));
        this.rename = Suppliers.memoize(() -> new RenameClient(baseClient));
    }

    public RemoveClient remove() {
        return this.remove.get();
    }

    public RenameClient rename() {
        return this.rename.get();
    }
}
