
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.email.bounce.remove;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.email.bounce.remove.params.CreateRequest;


public class RemoveClient {
    protected final BaseClient baseClient;

    public RemoveClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * Remove Hard Bounced Emails
    *
    * > Use this endpoint to remove email addresses from your Braze bounce list.
    *
    *
    * We will also remove them from the bounce list maintained by your email provider.
    *
    * To use this endpoint, you’ll need to generate an API key with the `email.bounce.remove` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `email` | Required | String or array | String email address to modify, or an array of up to 50 email addresses to modify. |
    *
    * POST /email/bounce/remove
    */
    public Map<?, ?> create(CreateRequest request) {
        return create(request, null);
    }


    /**
    * Remove Hard Bounced Emails
    *
    * > Use this endpoint to remove email addresses from your Braze bounce list.
    *
    *
    * We will also remove them from the bounce list maintained by your email provider.
    *
    * To use this endpoint, you’ll need to generate an API key with the `email.bounce.remove` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Request parameters
    *
    * | Parameter | Required | Data Type | Description |
    * | --- | --- | --- | --- |
    * | `email` | Required | String or array | String email address to modify, or an array of up to 50 email addresses to modify. |
    *
    * POST /email/bounce/remove
    */
    public Map<?, ?> create(CreateRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/email/bounce/remove")
            .method("POST")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .setJsonBody(request.getData())
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
