
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.resources.campaigns.dataseries.params.ListRequest;
import org.junit.jupiter.api.Test;


public final class CampaignsDataSeriesTestClient {
    @Test
    void testList200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.campaigns().dataSeries().list(ListRequest
                                                 .builder()
                                                 .campaignId("{{campaign_identifier}}")
                                                 .endingAt("2020-06-28T23:59:59-5:00")
                                                 .length(7)
                                                 .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
    @Test
    void testList200SuccessRequiredOnly() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.campaigns().dataSeries().list(ListRequest
                                                 .builder()
                                                 .campaignId("{{campaign_identifier}}")
                                                 .endingAt("2020-06-28T23:59:59-5:00")
                                                 .length(7)
                                                 .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
