
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.CanvasTriggerScheduleDeleteCreateBody;
import com.yourorg.brazejava.resources.canvas.trigger.schedule.delete.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class CanvasTriggerScheduleDeleteTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.canvas().trigger().schedule().delete().create(CreateRequest
                    .builder()
                    .data(CanvasTriggerScheduleDeleteCreateBody
                          .builder()
                          .canvasId("string")
                          .scheduleId("string")
                          .build())
                    .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
