
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.resources.canvas.dataseries.params.ListRequest;
import org.junit.jupiter.api.Test;


public final class CanvasDataSeriesTestClient {
    @Test
    void testList200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.canvas().dataSeries().list(ListRequest
                                              .builder()
                                              .canvasId("{{canvas_id}}")
                                              .endingAt("2018-05-30T23:59:59-5:00")
                                              .includeDeletedStepData(true)
                                              .includeStepBreakdown(true)
                                              .includeVariantBreakdown(true)
                                              .length(10)
                                              .startingAt("2018-05-28T23:59:59-5:00")
                                              .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
    @Test
    void testList200SuccessRequiredOnly() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.canvas().dataSeries().list(ListRequest
                                              .builder()
                                              .canvasId("{{canvas_id}}")
                                              .endingAt("2018-05-30T23:59:59-5:00")
                                              .includeDeletedStepData(true)
                                              .includeStepBreakdown(true)
                                              .includeVariantBreakdown(true)
                                              .length(10)
                                              .startingAt("2018-05-28T23:59:59-5:00")
                                              .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
