
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import java.util.List;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.ContentBlocksUpdateCreateBody;
import com.yourorg.brazejava.resources.contentblocks.update.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class ContentBlocksUpdateTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.contentBlocks().update().create(CreateRequest
                                                   .builder()
                                                   .data(ContentBlocksUpdateCreateBody
                                                           .builder()
                                                           .content("string")
                                                           .contentBlockId("string")
                                                           .description("string")
                                                           .name("string")
                                                           .state("string")
                                                           .tags(List.of(
                                                                   "string"
                                                                   ))
                                                           .build())
                                                   .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
