
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.EmailStatusCreateBody;
import com.yourorg.brazejava.resources.email.status.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class EmailStatusTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.email().status().create(CreateRequest
                                           .builder()
                                           .data(EmailStatusCreateBody
                                                 .builder()
                                                 .email("mail@example.com")
                                                 .subscriptionState("string")
                                                 .build())
                                           .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
