
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.EmailSpamRemoveCreateBody;
import com.yourorg.brazejava.resources.email.spam.remove.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class EmailSpamRemoveTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.email().spam().remove().create(CreateRequest
                                                  .builder()
                                                  .data(EmailSpamRemoveCreateBody
                                                          .builder()
                                                          .email("mail@example.com")
                                                          .build())
                                                  .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
