
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import java.util.List;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.EmailBlacklistCreateBody;
import com.yourorg.brazejava.resources.email.blacklist.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class EmailBlacklistTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.email().blacklist().create(CreateRequest
                                              .builder()
                                              .data(EmailBlacklistCreateBody
                                                    .builder()
                                                    .email(List.of(
                                                            "string"
                                                            ))
                                                    .build())
                                              .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
