
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.resources.events.dataseries.params.ListRequest;
import org.junit.jupiter.api.Test;


public final class EventsDataSeriesTestClient {
    @Test
    void testList200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.events().dataSeries().list(ListRequest
                                              .builder()
                                              .appId("{{app_identifier}}")
                                              .endingAt("2014-12-10T23:59:59-05:00")
                                              .event("event_name")
                                              .length(24)
                                              .segmentId("{{segment_identifier}}")
                                              .unit("hour")
                                              .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
    @Test
    void testList200SuccessRequiredOnly() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.events().dataSeries().list(ListRequest
                                              .builder()
                                              .appId("{{app_identifier}}")
                                              .endingAt("2014-12-10T23:59:59-05:00")
                                              .event("event_name")
                                              .length(24)
                                              .segmentId("{{segment_identifier}}")
                                              .unit("hour")
                                              .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
