
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.resources.kpi.dau.dataseries.params.ListRequest;
import org.junit.jupiter.api.Test;


public final class KpiDauDataSeriesTestClient {
    @Test
    void testList200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.kpi().dau().dataSeries().list(ListRequest
                                                 .builder()
                                                 .appId("{{app_identifier}}")
                                                 .endingAt("2018-06-28T23:59:59-5:00")
                                                 .length(10)
                                                 .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
    @Test
    void testList200SuccessRequiredOnly() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.kpi().dau().dataSeries().list(ListRequest
                                                 .builder()
                                                 .appId("{{app_identifier}}")
                                                 .endingAt("2018-06-28T23:59:59-5:00")
                                                 .length(10)
                                                 .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
