
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import java.util.List;
import java.util.Map;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.MessagesSendCreateBody;
import com.yourorg.brazejava.model.MessagesSendCreateBodyAudience;
import com.yourorg.brazejava.model.MessagesSendCreateBodyMessages;
import com.yourorg.brazejava.model.MessagesSendCreateBodyUserAliases;
import com.yourorg.brazejava.resources.messages.send.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class MessagesSendTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.messages().send().create(CreateRequest
                                            .builder()
                                            .data(MessagesSendCreateBody
                                                  .builder()
                                                  .audience(MessagesSendCreateBodyAudience
                                                          .builder()
                                                          .and(List.of(
                                                                  Map.ofEntries(

                                                                  )
                                                                  ))
                                                          .build())
                                                  .broadcast("string")
                                                  .campaignId("string")
                                                  .externalUserIds("string")
                                                  .messages(MessagesSendCreateBodyMessages
                                                          .builder()
                                                          .androidPush("string")
                                                          .applePush("string")
                                                          .contentCard("string")
                                                          .email("string")
                                                          .kindlePush("string")
                                                          .webPush("string")
                                                          .windowsPhone8Push("string")
                                                          .windowsUniversalPush("string")
                                                          .build())
                                                  .overrideFrequencyCapping("string")
                                                  .recipientSubscriptionState("string")
                                                  .segmentId("string")
                                                  .sendId("string")
                                                  .userAliases(MessagesSendCreateBodyUserAliases
                                                          .builder()
                                                          .aliasLabel("string")
                                                          .aliasName("string")
                                                          .build())
                                                  .build())
                                            .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
