
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.MessagesLiveActivityUpdateCreateBody;
import com.yourorg.brazejava.model.MessagesLiveActivityUpdateCreateBodyContentState;
import com.yourorg.brazejava.model.MessagesLiveActivityUpdateCreateBodyNotification;
import com.yourorg.brazejava.model.MessagesLiveActivityUpdateCreateBodyNotificationAlert;
import com.yourorg.brazejava.resources.messages.liveactivity.update.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class MessagesLiveActivityUpdateTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.messages().liveActivity().update().create(CreateRequest
                    .builder()
                    .data(MessagesLiveActivityUpdateCreateBody
                          .builder()
                          .activityId("string")
                          .appId("string")
                          .contentState(MessagesLiveActivityUpdateCreateBodyContentState
                                        .builder()
                                        .teamOneScore(123)
                                        .teamTwoScore(123)
                                        .build())
                          .dismissalDate("1970-01-01T00:00:00")
                          .endActivity(true)
                          .notification(MessagesLiveActivityUpdateCreateBodyNotification
                                        .builder()
                                        .alert(MessagesLiveActivityUpdateCreateBodyNotificationAlert
                                               .builder()
                                               .body("string")
                                               .title("string")
                                               .build())
                                        .build())
                          .staleDate("1970-01-01T00:00:00")
                          .build())
                    .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
