
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.MessagesScheduleUpdateCreateBody;
import com.yourorg.brazejava.model.MessagesScheduleUpdateCreateBodyMessages;
import com.yourorg.brazejava.model.MessagesScheduleUpdateCreateBodyMessagesAndroidPush;
import com.yourorg.brazejava.model.MessagesScheduleUpdateCreateBodyMessagesApplePush;
import com.yourorg.brazejava.model.MessagesScheduleUpdateCreateBodyMessagesSms;
import com.yourorg.brazejava.model.MessagesScheduleUpdateCreateBodySchedule;
import com.yourorg.brazejava.resources.messages.schedule.update.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class MessagesScheduleUpdateTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.messages().schedule().update().create(CreateRequest
                    .builder()
                    .data(MessagesScheduleUpdateCreateBody
                          .builder()
                          .messages(MessagesScheduleUpdateCreateBodyMessages
                                    .builder()
                                    .androidPush(MessagesScheduleUpdateCreateBodyMessagesAndroidPush
                                                 .builder()
                                                 .alert("string")
                                                 .title("string")
                                                 .build())
                                    .applePush(MessagesScheduleUpdateCreateBodyMessagesApplePush
                                               .builder()
                                               .alert("string")
                                               .badge(123)
                                               .build())
                                    .sms(MessagesScheduleUpdateCreateBodyMessagesSms
                                         .builder()
                                         .appId("string")
                                         .body("string")
                                         .messageVariationId("string")
                                         .subscriptionGroupId("string")
                                         .build())
                                    .build())
                          .schedule(MessagesScheduleUpdateCreateBodySchedule
                                    .builder()
                                    .time("1970-01-01T00:00:00")
                                    .build())
                          .scheduleId("string")
                          .build())
                    .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
