
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import java.util.List;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.SmsInvalidPhoneNumbersRemoveCreateBody;
import com.yourorg.brazejava.resources.sms.invalidphonenumbers.remove.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class SmsInvalidPhoneNumbersRemoveTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.sms().invalidPhoneNumbers().remove().create(CreateRequest
                    .builder()
                    .data(SmsInvalidPhoneNumbersRemoveCreateBody
                          .builder()
                          .phoneNumbers(List.of(
                                            "string"
                                        ))
                          .build())
                    .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
