
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.resources.subscription.status.get.params.ListRequest;
import org.junit.jupiter.api.Test;


public final class SubscriptionStatusGetTestClient {
    @Test
    void testList200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.subscription().status().get().list(ListRequest
                    .builder()
                    .externalId("{{external_identifier}}")
                    .phone("+11112223333")
                    .subscriptionGroupId("{{subscription_group_id}}")
                    .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
    @Test
    void testList200SuccessRequiredOnly() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.subscription().status().get().list(ListRequest
                    .builder()
                    .externalId("{{external_identifier}}")
                    .phone("+11112223333")
                    .subscriptionGroupId("{{subscription_group_id}}")
                    .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
