
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import java.util.List;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.TransactionalV1CampaignsSendCreateBody;
import com.yourorg.brazejava.model.TransactionalV1CampaignsSendCreateBodyRecipientItem;
import com.yourorg.brazejava.model.TransactionalV1CampaignsSendCreateBodyTriggerProperties;
import com.yourorg.brazejava.resources.transactional.v1.campaigns.send.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class TransactionalV1CampaignsSendTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.transactional().v1().campaigns().send().create(CreateRequest
                    .builder()
                    .data(TransactionalV1CampaignsSendCreateBody
                          .builder()
                          .externalSendId("string")
                          .recipient(List.of(
                                         TransactionalV1CampaignsSendCreateBodyRecipientItem
                                         .builder()
                                         .externalUserId("string")
                                         .build()
                                     ))
                          .triggerProperties(TransactionalV1CampaignsSendCreateBodyTriggerProperties
                                             .builder()
                                             .exampleIntegerProperty("string")
                                             .exampleStringProperty("string")
                                             .build())
                          .build())
                    .campaignId("string")
                    .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
