
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import java.util.List;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.UsersExternalIdsRenameCreateBody;
import com.yourorg.brazejava.model.UsersExternalIdsRenameCreateBodyExternalIdRenamesItem;
import com.yourorg.brazejava.resources.users.externalids.rename.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class UsersExternalIdsRenameTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.users().externalIds().rename().create(CreateRequest
                    .builder()
                    .data(UsersExternalIdsRenameCreateBody
                          .builder()
                          .externalIdRenames(List.of(
                                                 UsersExternalIdsRenameCreateBodyExternalIdRenamesItem
                                                 .builder()
                                                 .currentExternalId("string")
                                                 .newExternalId("string")
                                                 .build()
                                             ))
                          .build())
                    .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
