
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import java.util.List;

import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.model.UsersExportGlobalControlGroupCreateBody;
import com.yourorg.brazejava.resources.users.export.globalcontrolgroup.params.CreateRequest;
import org.junit.jupiter.api.Test;


public final class UsersExportGlobalControlGroupTestClient {
    @Test
    void testCreate200SuccessAllParams() {
        Client client = Client
                        .builder()
                        .environment(Environment.MOCK_SERVER)
                        .withBearerAuth("API_TOKEN")
                        .build();

        try {
            client.users().export().globalControlGroup().create(CreateRequest
                    .builder()
                    .data(UsersExportGlobalControlGroupCreateBody
                          .builder()
                          .callbackEndpoint("string")
                          .fieldsToExport(List.of(
                                              "string"
                                          ))
                          .outputFormat("string")
                          .build())
                    .build());
        } catch (ApiException e) {
            System.err.println("Error msg: " + e.toString());
            throw e;
        }
    }
}
