
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava;

import com.yourorg.brazejava.core.AuthBearer;
import com.yourorg.brazejava.core.BaseClient;


public final class ClientBuilder {

    private final BaseClient.Builder baseClientBuilder = BaseClient.builder();
    private Environment environment = Environment.ENVIRONMENT;
    public ClientBuilder environment(Environment environment) {
        this.environment = environment;
        return this;
    }
    public ClientBuilder url(String url) {
        this.environment = Environment.custom(url);
        return this;
    }
    public Client build() {
        baseClientBuilder.baseUrl(this.environment);
        return new Client(baseClientBuilder.build());
    }

    public ClientBuilder withBearerAuth(String token) {
        this.baseClientBuilder.addAuth("BearerAuth", new AuthBearer(token));
        return this;
    }

}
