
/**
 * Generated by Sideko (sideko.dev)
 **/

package com.yourorg.brazejava.core;

public interface AuthProvider {

    public void setValue(String val);

    public HttpRequestBuilder addAuth(HttpRequestBuilder builder);

}
