
/**
 * Generated by Sideko (sideko.dev)
 **/


package com.yourorg.brazejava.resources.feed.details;

import java.io.IOException;
import java.util.Map;

import com.fasterxml.jackson.core.type.TypeReference;
import com.yourorg.brazejava.core.ApiException;
import com.yourorg.brazejava.core.BaseClient;
import com.yourorg.brazejava.core.HttpRequestBuilder;
import com.yourorg.brazejava.core.RequestOptions;
import com.yourorg.brazejava.core.ResponseHandler;
import com.yourorg.brazejava.resources.feed.details.params.ListRequest;


public class DetailsClient {
    protected final BaseClient baseClient;

    public DetailsClient(BaseClient baseClient) {
        this.baseClient = baseClient;

    }

    /**
    * Export News Feed Cards Details
    *
    * > Use this endpoint to retrieve relevant information on a card, which can be identified by the `card_id`.
    *
    *
    * Note: If you are using our [older navigation](https://www.braze.com/docs/navigation), `card_id` can be found at **Developer Console > API Settings**.
    *
    * To use this endpoint, you’ll need to generate an API key with the `feed.details` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *     "message": (required, string) The status of the export, returns 'success' when completed without errors,
    *     "created_at" : (string) Date created as ISO 8601 date,
    *     "updated_at" : (string) Date last updated as ISO 8601 date,
    *     "name" : (string) Card name,
    *     "publish_at" : (string) Date card was published as ISO 8601 date,
    *     "end_at" : (string) Date card will stop displaying for users as ISO 8601 date,
    *     "tags" : (array) Tag names associated with the card,
    *     "title" : (string) Title of the card,
    *     "image_url" : (string) Image URL used by this card,
    *     "extras" : (dictionary) Dictionary containing key-value pair data attached to this card,
    *     "description" : (string) Description text used by this card,
    *     "archived": (boolean) whether this Card is archived,
    *     "draft": (boolean) whether this Card is a draft,
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /feed/details
    */
    public Map<?, ?> list() {
        return list(ListRequest.builder().build(), null);
    }


    /**
    * Export News Feed Cards Details
    *
    * > Use this endpoint to retrieve relevant information on a card, which can be identified by the `card_id`.
    *
    *
    * Note: If you are using our [older navigation](https://www.braze.com/docs/navigation), `card_id` can be found at **Developer Console > API Settings**.
    *
    * To use this endpoint, you’ll need to generate an API key with the `feed.details` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *     "message": (required, string) The status of the export, returns 'success' when completed without errors,
    *     "created_at" : (string) Date created as ISO 8601 date,
    *     "updated_at" : (string) Date last updated as ISO 8601 date,
    *     "name" : (string) Card name,
    *     "publish_at" : (string) Date card was published as ISO 8601 date,
    *     "end_at" : (string) Date card will stop displaying for users as ISO 8601 date,
    *     "tags" : (array) Tag names associated with the card,
    *     "title" : (string) Title of the card,
    *     "image_url" : (string) Image URL used by this card,
    *     "extras" : (dictionary) Dictionary containing key-value pair data attached to this card,
    *     "description" : (string) Description text used by this card,
    *     "archived": (boolean) whether this Card is archived,
    *     "draft": (boolean) whether this Card is a draft,
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /feed/details
    */
    public Map<?, ?> list(ListRequest request) {
        return list(request, null);
    }


    /**
    * Export News Feed Cards Details
    *
    * > Use this endpoint to retrieve relevant information on a card, which can be identified by the `card_id`.
    *
    *
    * Note: If you are using our [older navigation](https://www.braze.com/docs/navigation), `card_id` can be found at **Developer Console > API Settings**.
    *
    * To use this endpoint, you’ll need to generate an API key with the `feed.details` permission.
    *
    * ## Rate limit
    *
    * We apply the default Braze rate limit of 250,000 requests per hour to this endpoint, as documented in [API rate limits](https://www.braze.com/docs/api/api_limits/).
    *
    * ## Response
    *
    * ``` json
    * Content-Type: application/json
    * Authorization: Bearer YOUR-REST-API-KEY
    * {
    *     "message": (required, string) The status of the export, returns 'success' when completed without errors,
    *     "created_at" : (string) Date created as ISO 8601 date,
    *     "updated_at" : (string) Date last updated as ISO 8601 date,
    *     "name" : (string) Card name,
    *     "publish_at" : (string) Date card was published as ISO 8601 date,
    *     "end_at" : (string) Date card will stop displaying for users as ISO 8601 date,
    *     "tags" : (array) Tag names associated with the card,
    *     "title" : (string) Title of the card,
    *     "image_url" : (string) Image URL used by this card,
    *     "extras" : (dictionary) Dictionary containing key-value pair data attached to this card,
    *     "description" : (string) Description text used by this card,
    *     "archived": (boolean) whether this Card is archived,
    *     "draft": (boolean) whether this Card is a draft,
    * }
    *
    * ```
    *
    * > **Tip:** For help with CSV and API exports, visit [Export troubleshooting](https://www.braze.com/docs/user_guide/data_and_analytics/export_braze_data/export_troubleshooting/).
    *
    * GET /feed/details
    */
    public Map<?, ?> list(ListRequest request, RequestOptions requestOptions) {

        try {
            okhttp3.Response response = new HttpRequestBuilder()
            .baseUrl(this.baseClient.baseUrl())
            .path("/feed/details")
            .addQueryParam("card_id", request.getCardId(), "form", true)
            .method("GET")
            .addAuth(baseClient.getAuth("BearerAuth"))
            .execute();
            return ResponseHandler.processJsonResponse(response, new TypeReference<Map<?, ?>>() {});
        } catch (IOException e) {
            throw new ApiException("Error executing HTTP request", e);
        }
    }


}
